### ISSUE TITLE
Number of lines won't show

### ISSUE THREAD

**Issue by JacobCZ** [Block8/PHPCI#1004]
Hi, I've just installed PHPCI and I've noticed, that when i start a new build, there's an empty box saying Lines of Code, but when the build is completed, that box just disappears and nothing is shown. What could be causing this problem?

**Comment by tvbeek** [comment]
You need to add the phploc plugin to your phpci.yml
https://github.com/Block8/PHPCI/wiki/PHP-Loc-Plugin

**Comment by JacobCZ** [comment]
Oh, I see... Thanks.

**Comment by tvbeek** [comment]
Can you close the issue if you have it working?
