### ISSUE TITLE
Could not find phpcpd

### ISSUE THREAD

**Issue by maxgu** [Block8/PHPCI#1017]
```yml
RUNNING PLUGIN: php_cpd
Could not find phpcpd
```

How it works?
your composer.json not contain require: "sebastian/phpcpd"
and in vendor/bin phpcpd not exists

**Comment by delormejonathan** [comment]
Did you try to add the plugin ?
Admin Options > Plugins > Search package > phpcpd > Install
You will have a new entry in your composer.json, you have just to run a **composer update**.

**Comment by maxgu** [comment]
No, but I was tried and all works, thanks

**Comment by mavimo** [comment]
@maxgu please close the issue if fixed.
