### ISSUE TITLE
Build status images do not work

### ISSUE THREAD

**Issue by pdiveris** [Block8/PHPCI#1018]
Hi, I got the status image working at one stage yesterday. It appears that you are using a 3rd party image make, I didn't write down the .io url but it sees timing out now (I get a 504 bad gateway from my nginx). Any ideas? I am demonstrating the whole lot tomorrow! Thanks

http://ci.bentleysoft.com/build-status/image/1

(this is should be a successful  build image).
 Your's doesn't work either! http://phpci.block8.net/build-status/image/2

**Comment by tvbeek** [comment]
Both urls are working for me, didn't you have any other failure?

**Comment by pdiveris** [comment]
They work now. It seems that shield.io was thinking out. Thanks for getting back to me

**Comment by tvbeek** [comment]
@pdiveris so this can be closed?

**Comment by pdiveris** [comment]
Indeed, thanks!

> Tobias van Beek <mailto:notifications@github.com>
> 25 June 2015 11:00
>
> @pdiveris <https://github.com/pdiveris> so this can be closed?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Block8/PHPCI/issues/1018#issuecomment-115195880>.
>

-- 
Sent from Postbox 
<https://www.postbox-inc.com/?utm_source=email&utm_medium=siglink&utm_campaign=reach>
