### ISSUE TITLE
Do not remove index.php from links

### ISSUE THREAD

**Issue by isbkch** [Block8/PHPCI#1034]
I have an issue with the mod_rewrite apparently but in order for the app to work, I need to add "index.php" to the urls. I'm not that familiar with Synfony, but the solution should be simple I guess, I just want to leave the "index.php" in the URL. 

I changed PHPCI_URL in vars.php but this break the theme.

Is there a way to do that without adding a new constant that point to the correct assets folder then assigning it to all view ?
Thank you

**Comment by dancryer** [comment]
I'm afraid PHPCI requires that it is set up with proper rewrite rules in place, we won't be adding support for leaving index.php in the URL.
