### ISSUE TITLE
Slave agents

### ISSUE THREAD

**Issue by apgubarev** [Block8/PHPCI#1046]
All modern systems support the ability to run their tasks on remote servers via agents. My opinion is that this is a very important function. Do you plan to implementation of this function in the near future?

**Comment by tvbeek** [comment]
There ins't any plan for this, feel free to create a pr to add it

**Comment by dancryer** [comment]
This is not correct. PHPCI already supports this... 

With v1.6 (current stable) you can run a copy of PHPCI on your web server, and a copy on some other server running the daemon, and it'll work just fine. We do this for Hosted PHPCI currently.

With v1.7 (next release) - We're adding the ability to run PHPCI as a worker, using a beanstalkd-based queue.
