### ISSUE TITLE
phpunit - no TAP log found

### ISSUE THREAD

**Issue by craigwillis85** [Block8/PHPCI#1047]
Hi

I'm not sure If anyone will help me with this, since the project seems to have completely died..

I'm trying to run my `phpunit` tests using PHPCI.

I have installed `xdebug` and that is all fine. 

The issue I'm having, is everytime PHPCI runs and attempts to run my phpunit tests, I get the following:

`RunCommand.ERROR: Exception: No TAP log found, please check the configuration.`

When I check what command PHPCI is running for phpunit, I see the following:

`php /home/sites/myapp/PHPCI/build/171/bin//phpunit --tap --stderr /home/sites/myapp/PHPCI/build/171/tests/`

Running this in the command line, returns no errors, so I'm not sure what is going on.

I've tried all sorts of parameters passed to phpunit, but I always get the exact same error

Can anyone help? @dancryer, @mavimo, @tvbeek

**Comment by adamazing** [comment]
May be a red herring, but when you run the command at the command line, what user are you logged-in as? And as which user does phpci run?

**Comment by craigwillis85** [comment]
@adamazing I usually SSH into the server (as me - I have sudo privileges) and just run:

`php console phpci:run-builds`

I'm not sure why this is happening.

**Comment by craigwillis85** [comment]
@adamazing so it would seem it was an issue with my `phpunit.xml` file. I have just stripped it back and now I seem to see the TAP report.

I'll close this issue.

**Comment by craigwillis85** [comment]
I'm reopening this I now have another issue.

When the TAP report is generated, I am getting a TAP error. The output is similar to the following:

    TAP version 13     
        ok 1 - CSVTest::getHeaders 
    ok 2 - CSVTest::setHeaders 
    ok 3 - CSVTest::getColumns 
   ok 4 - CSVTest::setColumns

You can see there is some whitespace before the first test, which when parsed by the TapParser fails.

Does anyone have any ideas?

**Comment by craigwillis85** [comment]
I had some whitespace in a test, which I have now fixed. Closing.
