### ISSUE TITLE
No Build feedback

### ISSUE THREAD

**Issue by xolf** [Block8/PHPCI#1057]
I have created a new project. Configured it like the wiki told me and when I'm trying to build the current repository, nearly nothing happens. 
![Screenshot](https://cloud.githubusercontent.com/assets/8250052/9801606/67a5d7ea-5814-11e5-9f8f-0d120b65d6d9.PNG)This page stays the same for ages. Starting new builds does not help. I have no idea, what I did wrong.

**Comment by mms-hamburg** [comment]
you have a daemon running to build ?
try this from console:
https://www.phptesting.org/wiki/Run-Builds-Using-a-Daemon

**Comment by mikebronner** [comment]
@xolf Are you still having this issue after trying to run the daemon, and if that didn't work, the cron job? If the cron job didn't work, you are likely missing some dependencies in your OS, like curl, crypt, etc.

Please try running the build command manually from your command line:
```sh
php /path/to/phpci/console phpci:run-builds
```

You will likely get an error there telling you what is missing. Please let us know if you still have issues after that (or close the issue if this resolves things). :) Good luck!

**Comment by dancryer** [comment]
Given that there is no "Build started" time in the screenshot, it has to be assumed the builder is not running. The wiki link above should help. :+1:
