### ISSUE TITLE
Wiki doesn't tell how to use daemon with docker

### ISSUE THREAD

**Issue by mikk150** [Block8/PHPCI#1058]
I'd like to run builds on seperate docker images(so it would be possible to even build multiple versions together) but wiki doesn't tell how to compile docker image nor how to use it

**Comment by tvbeek** [comment]
I beleave there isn't anything to provide it a.t.m. Maybe you can create it and send a pr

**Comment by mikk150** [comment]
There is Dockerfile, and it is able to run daemons in docker(enter command is daemonize)

**Comment by dancryer** [comment]
Hi @mikk150 - This isn't properly supported yet I'm afraid. There is a Dockerfile and it sort of works, but we wouldn't be prepared to document it yet as it is likely to break.
