### ISSUE TITLE
Email has huge composer log all the time? 

### ISSUE THREAD

**Issue by cerw** [Block8/PHPCI#1060]
Hello

The email is not very usefull i get always HUGE composer debug< how Do i Turn this off? I tried debug and does nothing? 

thanks

**Comment by tvbeek** [comment]
You can use the option template:short in the e-mail settings

I have add it to https://github.com/Block8/PHPCI/wiki/Email-plugin#configuration-options

**Comment by cerw** [comment]
Thanks will try.

**Comment by tvbeek** [comment]
I close this issue because I suspect it is clear. Feel free to reopen if needed
