### ISSUE TITLE
Gitlab projects not working properly

### ISSUE THREAD

**Issue by GeorgeGardiner** [Block8/PHPCI#1062]
For some reason "git@github.com" and an additional ".git" are being appended to clone string.

Executing: export GIT_SSH="/usr/share/nginx/phpci/PHPCI/build/37.sh" && git clone  -b master git@github.com:git@gitlab.modern-english.co.uk:internal/juicer.git.git "/"
[0;31mCloning into '/usr/share/nginx/phpci/PHPCI/build/37'...
Warning: Permanently added 'github.com' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[0m
[0;31mFailed to clone remote git repository.[0m
[0;31mException: Could not create a working copy.[0m
![screen shot 2015-09-25 at 12 11 05](https://cloud.githubusercontent.com/assets/5549378/10099134/af65ca20-637e-11e5-83bf-247bf41de3d7.png)

**Comment by tvbeek** [comment]
That is because you have selected github in the dropdown for hosted. It should be gitlab (looking to your url)

**Comment by GeorgeGardiner** [comment]
Thanks @tvbeek 

I've been debugging my setup for ages, think I'm going crazy. You were correct about the URL being broken because of this so closing the issue.. Unfortunately my setup is still broken for some reason.
