### ISSUE TITLE
More Samples in Wiki

### ISSUE THREAD

**Issue by andreustimm** [Block8/PHPCI#1064]
I think that lack more samples in Wiki. For exemple here:

https://www.phptesting.org/wiki/Lint-Plugin
https://www.phptesting.org/wiki/Atoum-Plugin
https://www.phptesting.org/wiki/Behat-Plugin
https://www.phptesting.org/wiki/Campfire-Plugin
https://www.phptesting.org/wiki/Grunt-Plugin

**Comment by mikebronner** [comment]
You're right ... I didn't get to those when I added examples for the other plugins. Will update these shortly. Sorry about that.

**Comment by andreustimm** [comment]
All right! If I can help. Tell me.

**Comment by mikebronner** [comment]
Please! :) If you can post usage samples here for any of the ones listed above, that would be great.

**Comment by andreustimm** [comment]
Please send me your phpci.yml or paste here.

**Comment by mikebronner** [comment]
Examples added. Will update if people post their working samples here.

**Comment by andreustimm** [comment]
I think that can close this issue.

Thanks!
