### ISSUE TITLE
Feedback on GH forks

### ISSUE THREAD

**Issue by stefanius** [Block8/PHPCI#1074]
In an organisation structure with private repositories, I face the following problem:

When an employee (lets say, Stefanius) forks a private repo and after developing I pushed my changes (PR) to the organisation-repo, the build on PHPCI will start.

But, after  that in my pull request the status is still 'yellow' (busy) for ever and it will not go red or green. So the only way to see of a build is correct, is to log on the PHPCI server.

Is this a bug or see I something over the head?

**Comment by Rhymond** [comment]
I think you talk about that, you need to run daemon for that, or cronjob:
https://github.com/Block8/PHPCI/wiki/Run-Builds-Using-a-Daemon

**Comment by dancryer** [comment]
I'm assuming this is now working. Please feel free to reopen if this is not the case.
