### ISSUE TITLE
Deleting builds on disk

### ISSUE THREAD

**Issue by craigwillis85** [Block8/PHPCI#1092]
Hi

I have a server where I'm running PHPCI. The HDD is quite small (I know I can resize), but I was wondering if there was any setting that deletes the build folder from the server after finishing?

The issue I'm having is that the disk fills up quite quickly, so I'm having to delete builds manually on the server to free up space

Thanks

**Comment by dancryer** [comment]
This is a bug. Strangely enough, it has just caused problems on Hosted PHPCI this morning.

You'll note that in the build log, the last line is always: "Removing build"  - but for some reason, that is not working presently.

**Comment by dancryer** [comment]
(I am looking into this now)

**Comment by REBELinBLUE** [comment]
👍

**Comment by dancryer** [comment]
This is fixed in https://github.com/Block8/PHPCI/commit/7f823b37cf3ea72773d792e4e459f0bcbb4d8b60

I'm afraid it is a big update, there's a lot of changes there.

**Comment by craigwillis85** [comment]
@dancryer I don't mind waiting for it to be in master.

**Comment by REBELinBLUE** [comment]
It is in master because someone forgot to branch. Pretty sure that is a shooting offence
