### ISSUE TITLE
JS fault PHPCI 1.7.0-beta1

### ISSUE THREAD

**Issue by Henk8** [Block8/PHPCI#1098]
I have installed the update and it looks pretty good!
I only get a javascript error in: assets/js/build-plugins/warnings.js.

On line 104:
self.chartData[i].data.push(parseInt(self.data[build][key]));

But data is not an object. I suppose the fix must be
self.chartData.datasets[i].data.push(parseInt(self.data[build][key]));

Can you confirm if this is the fix?

**Comment by juanf** [comment]
I had the same issue and your fix seems to work ok. Thanks.

**Comment by mikebronner** [comment]
Not able to duplicate this error. What steps are you taking to reproduce?

**Comment by juanf** [comment]
Nothing fancy, just viewing a build (I'm on firefox).
This is the error:
"TypeError: self.chartData[i] is undefined
self.chartData[i].data.push(parseInt(self.data[build][key]));"

Looking at the code, the fix suggested by @Henk8 is pretty straightforward.
Also there's a console.log() in there that you might want to remove.

**Comment by mikebronner** [comment]
Have you tried the latest dev-master? I think this issue and the console.log() have been fixed already (I'm running on dev-master, which is probably why I'm not seeing it.

**Comment by juanf** [comment]
I'm working with this repo on master: https://github.com/Block8/PHPCI

Here's the code:
https://github.com/Block8/PHPCI/blob/master/public/assets/js/build-plugins/warnings.js#L104
