### ISSUE TITLE
Lines of code does not work (1.7.0-beta1)

### ISSUE THREAD

**Issue by martinvenus** [Block8/PHPCI#1103]
Graph with lines of code is not generated.

![linesofcode](https://github-cloud.s3.amazonaws.com/assets/450706/10565581/479eea62-75d4-11e5-8c28-418d190993f7.png)

**Comment by REBELinBLUE** [comment]
I might be wrong, but I think you need the `php_loc` plugin in your `.phpci.yml`

**Comment by martinvenus** [comment]
Hi,

thank you very much. You were right.

**Comment by REBELinBLUE** [comment]
@dancryer Shouldn't the LOC graph be hidden of the php_loc plugin isn't used?

**Comment by mikebronner** [comment]
I agree with @REBELinBLUE :) :+1:

**Comment by martinvenus** [comment]
Agree. There should not be the graph if php_loc is not used. So I reopen the issue.
