### ISSUE TITLE
Maximum 5000 errors shown in build details (1.7.0-beta1)

### ISSUE THREAD

**Issue by martinvenus** [Block8/PHPCI#1104]
I have more than 5000 errors in one project. But in build details is shown only 5000. Actually there are 5342 errors.

![errors](https://github-cloud.s3.amazonaws.com/assets/450706/10565605/e15d5878-75d4-11e5-9232-7ac215580b7f.png)

**Comment by dancryer** [comment]
Gosh, I thought 5000 was an appropriately high number. I guess we need to double it!
