### ISSUE TITLE
Technical debt - cannot specify directory to check

### ISSUE THREAD

**Issue by martinvenus** [Block8/PHPCI#1105]
I would like to use technical debt only for some part of my code (for example I don't want to inspect vendor directory). Is it possible to add this parameter please?

**Comment by REBELinBLUE** [comment]
Currently technical debt will ignore anything defined in the global project ignore, presumably you have vendor ignored on a project level?

**Comment by martinvenus** [comment]
You are right, I ignore vendor in the global definition. But for technical debt I would like to ignore for example folder with some external javascript or css.

**Comment by REBELinBLUE** [comment]
Ah I see, it shouldn't be that difficult to do, I'll see if I can take a look at it sometime in the next few days

**Comment by martinvenus** [comment]
Thank you very much.

**Comment by REBELinBLUE** [comment]
Hmm, actually looking at the code, it should already allow an `ignore` option for the plugin. Can you post you `phpci.yml` ?

**Comment by martinvenus** [comment]
Hi,

sorry for late reply. You are right, `ignore` option works:
```
    technical_debt:
        allow_failures: false
        ignore:
            - "www"
            - "db/public"
```

I think that we can close this issue.

Thank you.
