### ISSUE TITLE
Support Portuguese

### ISSUE THREAD

**Issue by andreustimm** [Block8/PHPCI#1110]
Support Portuguese
I will go translate for portuguese in seven days It will be ready!

I Can?

**Comment by mikebronner** [comment]
Go for it :) The more languages the better!

**Comment by dancryer** [comment]
Yes, please do. :+1:

**Comment by wandersonwhcr** [comment]
:+1:

**Comment by ricardofontanelli** [comment]
Hi @andreustimm , have you finished the translation to PT-BR? I'm thinking about do it!

**Comment by andreustimm** [comment]
Hi @ricardofontanelli, i see that you make. I did not had time.
Thanks!
