### ISSUE TITLE
Errors are being added to the tab multiple times while waiting for the build to finish.

### ISSUE THREAD

**Issue by juanf** [Block8/PHPCI#1112]
Errors are being appended to the tab with every ajax call when the build is in progress.
If the build is already finished the errors are duplicated.

Steps to reproduce:

* Click on "Build Now" on the project page.
* Run "console phpci:run-builds" from the command line.
* Go to the "Errors" tab.

Result: Every error found so far keeps being added to the list.

I think cleaning the table on "build-updated" before doing the append seems to work.

DIFF:
```javascript
diff --git a/public/assets/js/build.js b/public/assets/js/build.js
index f783d8f..736e6f9 100644
--- a/public/assets/js/build.js
+++ b/public/assets/js/build.js
@@ -32,6 +32,7 @@ var Build = Class.extend({
             $('.build-started').data('date', self.buildData.started ? self.buildData.started : '');
             $('.build-finished').data('date', self.buildData.finished ? self.buildData.finished : '');
             $('#log pre').html(self.buildData.log);
+            $('.errors-table tbody').html('');
             $('.errors-table tbody').append(self.buildData.error_html);
 
             if (self.buildData.errors == 0) {
```
I'm working on master.
Thanks.

**Comment by REBELinBLUE** [comment]
:+1: @dancryer You said you were going to fix this, any objection to this fix?

**Comment by dancryer** [comment]
The controller should only be returning errors since the last time it checked, so we shouldn't need to clear the list...

**Comment by juanf** [comment]
The bug still exists when you load an already finished build.
