### ISSUE TITLE
PHP Fatal error:  Class 'PHPCI\\Controller' not found

### ISSUE THREAD

**Issue by CRTX** [Block8/PHPCI#1114]
There's this really annoying error that keeps popping up when trying to retrieve one of the assets.

I'm using version PHPCI version 1.6

PHP Fatal error:  Class 'PHPCI\\Controller' not found in b8framework/b8/Application.php on line 93

server: php.ci, request: "GET /assets/js/plugins/datepicker/locales/bootstrap-datepicker.en.js HTTP/1.1

**Comment by intech** [comment]
+1

**Comment by dancryer** [comment]
https://github.com/Block8/PHPCI/issues/1023#issuecomment-153323760
