### ISSUE TITLE
Duplicity in error report

### ISSUE THREAD

**Issue by martinvenus** [Block8/PHPCI#1130]
Hello,

I have 1 PHPCS error in commit (please see the attachment) but in errors tab there is it twice. This error is only once in database, so there is probably some mistake on frontend.

I'm using version from master branch (commit 6eb180ed5fd304e02764328f238c5b899b1d2fa3).

![screenshot](https://cloud.githubusercontent.com/assets/450706/11177404/ace51f40-8c45-11e5-8f3b-ffd111af70cc.png)

**Comment by REBELinBLUE** [comment]
@dancryer I thought you'd fixed this? https://github.com/Block8/PHPCI/issues/1112

**Comment by mikebronner** [comment]
I've been seeing the same duplication issues .

**Comment by mikk150** [comment]
I'm seeing same thing here
