### ISSUE TITLE
Unserialize error

### ISSUE THREAD

**Issue by CRTX** [Block8/PHPCI#1134]
I tried PHPCI before and it worked like a charm

However this time I tried to set it up again and I'm not able to build a project.

The following is what I get when I try to build a `GitLab` project.

```
Exception: Notice: unserialize(): Error at offset 0 of 2 bytes in phpci/PHPCI/Model/Project.php line 77
```
```
[2015-11-21 05:24:56] DaemoniseCommand.ERROR: Exception: Notice: unserialize(): Error at offset 0 of 2 bytes in /phpci/PHPCI/Model/Project.php line 77 {"buildID":"4"} []
```

I tried a little debugging and on line 77 this is the following line:

```
$data = unserialize($info);
```

I `var_dump`ed `$info` and I get the following

```
string(2) "[]"
```

Granted this is after reloading the page so I'm not sure if it helps.
If there's any way to debug and output the value when the error is triggered maybe I can help better.

**Comment by hiteshmahajan** [comment]
Facing same Issue any update on this ?

**Comment by CRTX** [comment]
@hiteshmahajan Yeah, found the answer here: https://github.com/Block8/PHPCI/issues/604#issuecomment-165194284

Basically use the git format for project urls

So this: `git@gitlab.com:owner/project.git`
Instead of this: `https://gitlab.com/owner/project.git`
