### ISSUE TITLE
Loading mixed (insecure) display content

### ISSUE THREAD

**Issue by MattMuffin** [Block8/PHPCI#1137]
Hello,

When enabling SSL over HTTP (HTTPS), I get the following message in firebug: Loading mixed (insecure) display content.

The problem is that I cannot login to the site unless I tweak firefox or safari into using mixed content.

This is ok when only a couple of us use the interface. It will quickly become bothersome as the team grows.

**Comment by dancryer** [comment]
@MattMuffin In your PHPCI/config.yml file, what's your PHPCI URL set to?

**Comment by MattMuffin** [comment]
Thank you @dancryer , I found the solution. Indeed, when declaring https as a URL in the config file, it seems like every link generated buy the app starts with HTTPS.
