### ISSUE TITLE
Cloning Handing

### ISSUE THREAD

**Issue by mrsimonbennett** [Block8/PHPCI#1148]
Hello, 

I am just trying to set up my first project in PHPCI.

When I go to build It stops on cloning.

![screen shot 2015-12-21 at 17 14 37](https://cloud.githubusercontent.com/assets/1471305/11936527/639bd004-a806-11e5-93bf-d92effef8d47.png)

Any pointers to where to look?

**Comment by mrsimonbennett** [comment]
Well I am not sure what I did but I have reached my next error
```
fatal: ambiguous argument 'Manual^!': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]
```

**Comment by zippy1981** [comment]
See this https://github.com/Block8/PHPCI/issues/1051#issuecomment-141104748

**Comment by mrsimonbennett** [comment]
Thanks @zippy1981  I am going to close this now as i just swapped versions and that fixed it :)
