### ISSUE TITLE
Specify php.ini Per Project

### ISSUE THREAD

**Issue by Fenikkusu** [Block8/PHPCI#1158]
I have projects that use differing versions of an installed extension. Because of this, I cannot run the same PHP-CI instance for all projects as only the actively enabled extension version will build properly. If I could specify the INI file to use on a per-project basis, then I could run them all through one PHP-CI instance without the need to constantly ssh into the server to swap the extension.

**Comment by olimorris** [comment]
Surely this is an issue with your server environment as opposed to PHPCI? realistically how could PHPCI load another PHP.ini file, reboot the PHP server and still be running?
