### ISSUE TITLE
I can login in the app

### ISSUE THREAD

**Issue by yriveiro** [Block8/PHPCI#1162]
Hi,

I can't login in phpci, I'm in an infinite loop in login screen and doesn't forward.

I installed the latest version of phpci from scratch following the install documentation available in a centos 7 vagrant vm, with nginx and mariadb.

![out](https://cloud.githubusercontent.com/assets/934763/12356497/f3333fa2-bb9a-11e5-9bff-bf5a3042e9de.gif)

**Comment by tvbeek** [comment]
Can you check if you have anything in your log? This can happen if php can't write the sessions.

**Comment by yriveiro** [comment]
Where the logs are written?

**Comment by tvbeek** [comment]
That depends on your settings, you can check it in your php.ini file

**Comment by yriveiro** [comment]
It works.

I think that should be a guard in console command ```php phpci:install``` to check if session path is writable. If not abort the installation, this can save a lot of time :D
