### ISSUE TITLE
MySQL syntax error on setup with MySQL 5.7

### ISSUE THREAD

**Issue by georaldc** [Block8/PHPCI#1170]
If you are using 5.7, I believe you will run into an UPDATE query error (and a PDO exception) with the build table when phinx migration tries to set a DEFAULT VALUE for the log column. I think this is due to strict mode being enabled by default. My fix was to remove the default value for that column (which is just an empty string) but I wonder if that would cause any side effects?

**Comment by milroyfraser** [comment]
+1

**Comment by dancryer** [comment]
This is fixed in v1.7 beta 3 (which will be released later today)
