### ISSUE TITLE
Help me understand PHPCI – what is a build?

### ISSUE THREAD

**Issue by geoidesic** [Block8/PHPCI#1173]
Please forgive me if this is a silly question. I'm not hating on phpci, I'm just trying to understand it:

PHP is a scripting language... so one doesn't really "build" an application like you do in C++. You just write the code and the application runs. So I'm not grokking the concept of what a "build" is?

At first I thought it was about deployment – because that would be super useful – a button on your server's dev portal that you click and hey presto the latest version is deployed to production from git. But that's apparently not what phpci does.

It looks like I can use it to run unit tests... but then I could just run the tests without phpci. So again I'm not understanding what to expect from a "build". What's the benefit of performing a build?

At the moment it seems counter-productive to me:- like a (much) slower version of git pull but which clones the code into a folder that doesn't have a vhost, so you can't browse it.

Confused.

**Comment by adamazing** [comment]
"It looks like I can use it to run unit tests... but then I could just run
the tests without phpci."

CI stands for Continuous Integration (
https://en.wikipedia.org/wiki/Continuous_integration)

E.g. You can set up a git hook that automatically pulls every new commit
and runs through your tests without you having to do anything.

**Comment by geoidesic** [comment]
Ok so it's really all about automated testing. Nothing else?

**Comment by tvbeek** [comment]
Yes, see https://github.com/Block8/PHPCI#what-it-does

(Can you close the issue if this answer your question?)

**Comment by geoidesic** [comment]
Sorry but just a further clarification... why does one have build 1, build 2, build 3. Why not just overwrite the same build each time?

**Comment by tvbeek** [comment]
Because it hold the results of the build (success/fail, number of lines, log, ...) if you reuse the build number you can't refer to the results

**Comment by geoidesic** [comment]
ok thanks.
