### ISSUE TITLE
Configure PHPCI to build the project at periodic intervals

### ISSUE THREAD

**Issue by MitchProbst** [Block8/PHPCI#1176]
I recently began using PHPCI and I am wondering if it is possible to have PHPCI build my project every night.  It is hosted on gitlab and I have played with the webhooks that will have it build on every commit/tag/merge request etc... but none of the options achieve what I am looking for.  I want to set up a build to happen based on time, not on event. Is this possible?

**Comment by dancryer** [comment]
Your best bet would be to do this via cron. 

Create a shell script (`/path/to/phpci/build-projects.sh`):

```sh
#!/usr/bin/env sh

cd /path/to/phpci
./console phpci:create-build {PROJECT_ID_HERE}
./console phpci:create-build {ANOTHER_PROJECT_ID_HERE}
./console phpci:run-builds
```

Then in cron:

```cron
0 17 * * * sh /path/to/phpci/build-projects.sh
```

This will create builds for your project(s) and then run them, once a day at 5PM. 

I've not tested the code, but it should be close enough to give you an idea of what you're doing. :+1:

**Comment by MitchProbst** [comment]
I tried to execute ./console phpci:create-build and got the error
```
[Symfony\Component\Console\Exception\CommandNotFoundException]
 Command "phpci:create-build" is not defined.
```
I attempted to get the version I am using by running `./console --version` and it only returns <p>Console Tool</p>
I installed phpci a week ago using composer so I assume I am on version 1.6.0
