### ISSUE TITLE
Enabling the rebelinblue/deployer plugin

### ISSUE THREAD

**Issue by pemenang** [Block8/PHPCI#1193]
Hi, I want to try using rebelinblue/deployer as describe in https://github.com/Block8/PHPCI/wiki/Deployer.

Installed the plugin via composer but somewhow I get this when running a build:

> RUNNING PLUGIN: deployer
> Plugin does not exist: deployer
> PLUGIN: FAILED

**Comment by GenericStudent** [comment]
What was the process you took in order to install the plugin?

Also what version of PHPCI are you running?

**Comment by pemenang** [comment]
PHPCI Version 1.6.0

I install the plugin through the Plugins page.
1. Search the package
2. Install
3. composer update

**Comment by GenericStudent** [comment]
Can you run the following at the root of your PHPCI folder and post the relevant section?

`./console phpci:rebuild -vvv`

I don't personally have a clue on your situation but I've found running these commands manually will assist in debug / troubleshooting.

**Comment by REBELinBLUE** [comment]
Someone else had this problem before, can you try running `composer dump-autoload`?

Are you using cronjobs to run builds? If you are using the daemon or the queue listener can you restart them to make sure it has picked up the plugin file?

**Comment by pemenang** [comment]
Sorry for the late reply. Was away for a while. Anyway, I started from scratch:

1. remove the plugin
2. composer update
3. install the plugin via the plugin page. choosed 0.0.33
4. composer update

and get this result:

> Loading composer repositories with package information
>Updating dependencies (including require-dev)
>Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - Installation request for rebelinblue/deployer 0.0.33 -> satisfiable by rebelinblue/deployer[0.0.33].
>    - rebelinblue/deployer 0.0.33 requires andywer/js-localization dev-laravel-5 -> satisfiable by andywer/js-localization[dev-laravel-5] but these conflict with your requirements or minimum-stability

PHPCI version 0.60

**Comment by REBELinBLUE** [comment]
Ah, there seems to be some confusion here. https://github.com/REBELinBLUE/deployer is a completely separate app I work on, it isn't a plugin for PHPCI.

PHPCI has a plugin, included already https://github.com/Block8/PHPCI/blob/master/PHPCI/Plugin/Deployer.php which can call the webhook feature in Deployer to trigger a deployment on a successful build.

**Comment by pemenang** [comment]
I see. My mistake then.

That said, without installing the packages. I still getting same error at my first post. `Plugin does not exist: deployer`

Copy paste the command from wiki.. using my own url off course.

**Comment by REBELinBLUE** [comment]
https://github.com/Block8/PHPCI/tree/1.6.0/PHPCI/Plugin Version 1.6.0 doesn't appear to include the plugin

Added in the 1.7.0 betas by the looks of it

https://github.com/Block8/PHPCI/tree/1.7.0-beta1/PHPCI/Plugin
https://github.com/Block8/PHPCI/tree/1.7.0-beta2/PHPCI/Plugin

**Comment by pemenang** [comment]
Ah yes.. why didn't I check that first? *facepalm*

I'll wait for the official release.. Thank you
