### ISSUE TITLE
Run build when create new PR

### ISSUE THREAD

**Issue by lucasdealmeida** [Block8/PHPCI#1204]
Hi everyone, I would like know how I can make the PHPCI run build after create a new Pull Request, like the image bellow:
![screen shot 2016-04-10 at 4 40 32 pm](https://cloud.githubusercontent.com/assets/1371269/14412537/228751ce-ff3b-11e5-86dc-a573dbfa7525.png)
Thank you!

**Comment by dancryer** [comment]
Hi @lucasdealmeida - This guide on the wiki should help: https://github.com/Block8/PHPCI/wiki/Autobuilding-From-GitHub
