### ISSUE TITLE
Download latest version doesn't work (404) because of tag name typo?

### ISSUE THREAD

**Issue by bertoost** [Block8/PHPCI#1216]
### Expected behaviour

https://www.phptesting.org/install-phpci
Expecting v1.7.0 to get a downloadable archive

### Actual behaviour

I am getting a "Not found" message

### Steps to reproduce

Go to https://www.phptesting.org/install-phpci
Hit download of version 1.7.0

### Environment info
Operating System:
PHP Version:
MySQL Version:

### Logs or other output that would be helpful

Probably because the tag is "v1.7.0" instead of "1.7.0". The link on the website should be changed.

**Comment by dancryer** [comment]
Sorry I missed this, but 1.7.1 has been released now which means this is no longer a problem. :)
