### ISSUE TITLE
It is possible to run worker threads without PHPCI knowing about it

### ISSUE THREAD

**Issue by asgrim** [Block8/PHPCI#1231]
Running two worker threads means that the original PID gets "lost" essentially, so PHPCI no longer knows about it. This means a ghostly worker thread is still running, but using `./console phpci:daemon stop` won't kill it.

### Expected behaviour

I expect PHPCI to properly track processes it is running and to stop them so I don't have to manually hunt through the process list and kill them.

### Actual behaviour

There are PHPCI worker processes that can only be killed by looking at them in the process list and manually killing them.

### Steps to reproduce

* Run `nohup php ./daemonise phpci:daemonise >/dev/null 2>&1  &` twice.
* Run `./console phpci:daemon stop`, it will stop the most recent daemon
* Try to `./console phpci:daemon stop`, it will simply say `Not started` but another worker is still running.

### Environment info
Operating System: IBM i / AIX
PHP Version: 5.6

**Comment by dancryer** [comment]
Going forward, the recommended way to manage this is to use the worker mode instead, and use a proper process manager like supervisord to manage it. 

https://github.com/Block8/PHPCI/wiki/Run-Builds-Using-a-Worker
