### ISSUE TITLE
Socket-Error when trying to start build on Ubuntu 16.04 in a virtual machine

### ISSUE THREAD

**Issue by Robdebert** [Block8/PHPCI#1234]
I have this problem on a virtual-machine running ubuntu server 16.04.

Error-Message is:
`Warning: fsockopen(): unable to connect to localhost:11300 (Connection refused) in /var/www/phpci/vendor/pda/pheanstalk/src/Socket/StreamFunctions.php line 73`

What could i do here?
It is a fresh installed Ubuntu Server with Apache, PHP7, Mysql etc.

### Expected behaviour

* I don't know, as i have never reached the next page before. I would say: No error :-) *

### Actual behaviour

* Instead i see the message: Warning: fsockopen(): unable to connect to localhost:11300*

### Steps to reproduce

* Install it like described in the guide on a very clean ubuntu server 16.04 virtual machine. i used vbox on windows. add a new github project and click on "build". *

### Environment info
Operating System: ubuntu server 16.04 
PHP Version: 7.0
MySQL Version: 5.7.12

### Logs or other output that would be helpful
Please tell me, which logs you need, and i will upload them.

**Comment by REBELinBLUE** [comment]
Sounds like you don't have beanstalkd installed

**Comment by dancryer** [comment]
This is fixed in v1.7.1: https://github.com/Block8/PHPCI/releases/tag/1.7.1

As @REBELinBLUE mentioned, you either don't have beanstalkd or you haven't configured it properly in PHPCI.
