### ISSUE TITLE
Code Coverage Question

### ISSUE THREAD

**Issue by Fenikkusu** [Block8/PHPCI#1250]
I'm working on a quick plugin at the moment. After having created the plugin and creating the tests for the plugin, I wanted to run Humbug on the testing to make sure my testing is solid. When I did so, I came across a weird error. After looking into it, I learned that there are about 46 methods in the Test Suite that all have '@covers PHPUnit:execute' as part of the Doc Block.

As I understand it, '@covers' is intended to tell PHPUnit what methods are covered by a test. Okay, all fine and good...but why are all these tests saying they cover PHPUnit::execute()? Code Coverage dies here because it cannot execute that.

Because of this, you cannot run PHPUnit Code Coverage (Or Humbug) on the testing currently without doing a system wide removal of the annotation.

**Comment by dancryer** [comment]
If I'm honest, I have no idea why those annotations are there. I think perhaps they were copied and pasted from some sample code somewhere and never got modified? 

Feel free to submit a PR to remove them. :)
