### ISSUE TITLE
Hosted PHP.ci, attempt to get some sort of support

### ISSUE THREAD

**Issue by tjomamokrenko** [Block8/PHPCI#1276]
- [x] You're running the [latest release](https://github.com/Block8/PHPCI/releases/latest) version of PHPCI.
- [x] Ensure that you're running at least PHP 5.3.6, you can check this by running `php -v`
- [x] You've run `composer install --no-dev -o` from the root of your installation.
- [x] You have set up either the PHPCI [Worker](https://github.com/Block8/PHPCI/wiki/Run-Builds-Using-a-Worker), [Daemon](https://github.com/Block8/PHPCI/wiki/Run-Builds-Using-a-Daemon) or [Cron Job](https://github.com/Block8/PHPCI/wiki/Run-Builds-Using-Cron) to run builds.

### Expected behaviour

I wanted to use hosted PHP.ci.

I signed up (it's unclear during registration that username will be used as a part of domain because I am unfamiliar with .CI TLD! If I got it right I'd put my company name there)

I added a PHP7 project, I wanted it all to work as people usually expect a CI system to work.

### Actual behaviour

- Nowhere it is said that hosted PHP.ci is sticked to PHP 5.5 ❗️ 
- My subscription now has my first & last name right in the domain without the way to change it
- ~~No support channel is available except GitHub. Privacy?~~ ~~(found an email address in my inbox)~~ support is irresponsible 
- AdminLTE theme. Funny.

### Steps to reproduce

Just try use your product.

### Environment info
Operating System:
PHP Version:
MySQL Version:

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

### What do I want

I'd like to get a refund. 

artiom.mocreno@armoc.md
artiommocrenco.php.ci
*3491

Cheers,
Artiom Mocrenco.

**Comment by tjomamokrenko** [comment]
@dancryer @corpsee @meadsteve @Adirelle I want a refund which I have right to by law. Thanks 👍

**Comment by tjomamokrenko** [comment]
@dancryer @corpsee @meadsteve @Adirelle You are a company now and dealing with other company based on UK laws, so please, provide a refund.

https://www.gov.uk/accepting-returns-and-giving-refunds

**Comment by dancryer** [comment]
@tjomamokrenko Your subscription has been cancelled and your payment refunded.

For reference, your assessment of UK law on this matter is incorrect, as the product is not faulty, and does do as advertised. However, given that you cannot use the product we're happy to voluntarily refund your subscription payment.

**Comment by tjomamokrenko** [comment]
Thank you for a fast reply, @dancryer 

However, it states:

> **Online, mail and phone order sales**

> Online, mail and telephone order customers have the right to cancel their order for a limited time **even if the goods aren’t faulty**. Sales of this kind are known as ‘distance selling’.

> You must offer a refund to customers if they’ve told you **within 14 days** of receiving their goods that they want to cancel. They have another 14 days to return the goods once they’ve told you.

> You must refund the customer within 14 days of receiving the goods back. **They don’t have to provide a reason.**

> _https://www.gov.uk/accepting-returns-and-giving-refunds_

Thanks anyway and I hope you take in consideration issues I indicated to and improve the product. The idea and price is worth it! 👍
