### ISSUE TITLE
issue login after adding ssl

### ISSUE THREAD

**Issue by oitsem099** [Block8/PHPCI#1294]
Mixed Content: The page at 'https://phpci.website.com/session/login' was loaded over HTTPS, but requested an insecure image 'http://phpci.hybrain.co//assets/img/logo-large.png'. This content should also be served over HTTPS.
login:95 Mixed Content: The page at 'https://phpci.website.com/session/login' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://phpci.hybrain.co/session/login'. This endpoint should be made available over a secure connection.

does anyone know how to fix this?
I can't login after adding the ssl on our site.
its not showing a lock sign on the url side.
but all our other sub-domains are working fine

**Comment by dancryer** [comment]
You need to modify the URL setting in the `PHPCI/config.yml` file:

```yaml
phpci:
    url: 'https://phpci.website.com'
```
