### ISSUE TITLE
Question about .pdepend folder

### ISSUE THREAD

**Issue by sondoha** [Block8/PHPCI#1307]
Hello,

Thank you a lot for your awesome product :-) I love it so much!

I see the folder `.pdepend` grew to 2.9 GB. So my question is, may I clear this folder? How it affect to PHPCI app?

Thank you,
Son Do

**Comment by tvbeek** [comment]
Yes, this is a bug in pdepend and fixed in this commit from pdepend.
https://github.com/pdepend/pdepend/commit/56712b10c78a17f8305436c5a4ccdf3106107691
