### ISSUE TITLE
Add deployer

### ISSUE THREAD

**Issue by antonmedv** [Block8/PHPCI#1321]
Hi,

What about adding https://deployer.org as plugin?

**Comment by RichardLindhout** [comment]
https://github.com/Block8/PHPCI/wiki/Deployer

**Comment by RichardLindhout** [comment]
Only I would like to add a branch to deployer succes so the master calls a different webhook

**Comment by RichardLindhout** [comment]
Correction, it's in the $_POST!

**Comment by antonmedv** [comment]
I mean another deployer, not phpdeployer.

**Comment by RichardLindhout** [comment]
Ah, now I see, I also use deployer.org. Anyways I made a PHP file which executes deploy command based on post data of the other deployer.

**Comment by RichardLindhout** [comment]
I would alsof like a better plugin for deployer.org!
