### ISSUE TITLE
RUNNING PLUGIN: php_code_sniffer Exception: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1

### ISSUE THREAD

**Issue by cnizzardini** [Block8/PHPCI#1342]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ X] You're running the [latest release](https://github.com/Block8/PHPCI/releases/latest) version of PHPCI.
- [ X] Ensure that you're running at least PHP 5.3.6, you can check this by running `php -v`
- [ X] You've run `composer install --no-dev -o` from the root of your installation.
- [ X] You have set up either the PHPCI [Worker](https://github.com/Block8/PHPCI/wiki/Run-Builds-Using-a-Worker), [Daemon](https://github.com/Block8/PHPCI/wiki/Run-Builds-Using-a-Daemon) or [Cron Job](https://github.com/Block8/PHPCI/wiki/Run-Builds-Using-Cron) to run builds.

To help us better understand your issue, please answer the following.

### Expected behaviour

Should be able to log a message from the plugin.

### Actual behaviour

RUNNING PLUGIN: php_code_sniffer Exception: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1

### Steps to reproduce

Lots of crappy code in your project that php_code_sniffer does not like. I manually increased the data type on the column to LONGTEXT to avoid the issue for now.

### Environment info
Operating System: Ubuntu 16.04.3 LTS
PHP Version: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
MySQL Version: mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by Anoxia** [comment]
See #1215

**Comment by cnizzardini** [comment]
@Anoxia thanks, closing since its been reported already.
