### ISSUE TITLE
More documentation & more examples

### ISSUE THREAD

**Issue by sobi3ch** [Block8/PHPCI#198]
Hi guys, I'm totally new to this project and it looks very promising. Also I would like say you making excellent job. However after 2 days of non-stop playing around I found my self very confused about several basic (I think) things you can or can not do with PHPCI. 

Documentation wiki pages missing basic information how to use it. Installation process if fairly good, but when I've try to create my first phpci.yml file then I didn't have any example except this one https://github.com/Block8/PHPCI/wiki/Adding-PHPCI-Support-to-Your-Projects

Each plugin should have some real example. There are missing general example step by step how to create your FIRST project. This could be very useful for folks that are not so skilful in OS or/and PHP but they are willing to join (start using) this project.

Do you following travis-ci .yml configuration style or the above wiki page are everything that PHPCI support if so then this should be mention otherwise it could be great to have list of "functions" you can use in config file.

Last question is there any way to output message in output console? Using 'shell' plugin with 'echo' didn't work even when I try Phing with 'message' attribute didn't work.

thanks!

**Comment by yuwenhui** [comment]
+1
