### ISSUE TITLE
login redirect loop

### ISSUE THREAD

**Issue by firstactivemedia** [Block8/PHPCI#204]
Just cloned PHPCI and can't get it to work. The install went okay, and the DB has been created, but now I get redirect to /session/login which ends with a redirect loop

it appears validateSession is redirecting to the login page because I am not logged in

``` php
    protected function validateSession()
    {
        if (!empty($_SESSION['user_id'])) {
            $user = b8\Store\Factory::getStore('User')->getByPrimaryKey($_SESSION['user_id']);

            if ($user) {
                $_SESSION['user'] = $user;
                return true;
            }

            unset($_SESSION['user_id']);
        }

        if ($this->request->isAjax()) {
            $this->response->setResponseCode(401);
            $this->response->setContent('');
        } else {
            $this->response = new RedirectResponse($this->response);
            $this->response->setHeader('Location', PHPCI_URL.'session/login');
        }

        return false;
    }
```

Any ideas on what went wrong?

Running php v5.4 on centos

thanks :)

**Comment by kenyiu** [comment]
I am still facing the issue with nginx. Here is my config. 
Any ideas? Thanks.

```
upstream php {
        server 127.0.0.1:9000;
       # server unix:/var/run/php5-fpm.sock; #for PHP-FPM running on UNIX socket
}

server {
    listen 80;

    server_name phpci.app;
    root /home/vagrant/Codes/develop/phpci/public;

    error_log /var/log/nginx/phpci.error.log;
    access_log /var/log/nginx/phpci.access.log;

    location / {
        index index.php;
        try_files $uri @rewriteapp;
    }

    location @rewriteapp {
        rewrite ^(.*)$ /index.php/$1 last;
    }

    # pass the PHP scripts to FastCGI server from upstream phpfcgi
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param  HTTPS off;
    }
}
```

**Comment by lakshmi28gsrl** [comment]
Iam trying in localhost add htaccess code , mode_rewrite is enable but iam having same problem url http://localhost/PHPCI/session/login redirecting to 404. Can you help us in solving this issue.

**Comment by antidamage** [comment]
This is still an issue for me according to the log. Although the site front-end seems to be working, the builds are not taking place as far as I can tell. I've just done a fresh install. These errors are generated on every page view. Here's the log:

[Thu Apr 02 15:48:08.635548 2015] [:error] [pid 19630] [client 10.28.1.35:58381] PHP Fatal error:  Class 'PHPCI\\\\Controller' not found in /var/www/phpci/vendor/block8/b8framework/b8/Application.php on line 93, referer: http://phpci.adstats01.domain.com/project/view/1
[Thu Apr 02 15:48:08.638131 2015] [:error] [pid 19630] [client 10.28.1.35:58381] PHP Stack trace:, referer: http://phpci.adstats01.domain.com/project/view/1
[Thu Apr 02 15:48:08.639868 2015] [:error] [pid 19630] [client 10.28.1.35:58381] PHP   1. {main}() /var/www/phpci/public/index.php:0,referer: http://phpci.adstats01.domain.com/project/view/1
[Thu Apr 02 15:48:08.639967 2015] [:error] [pid 19630] [client 10.28.1.35:58381] PHP   2. PHPCI\\Application->handleRequest() /var/www/phpci/public/index.php:16, referer: http://phpci.adstats01.domain.com/project/view/1
[Thu Apr 02 15:48:08.640043 2015] [:error] [pid 19630] [client 10.28.1.35:58381] PHP   3. b8\\Application->handleRequest() /var/www/phpci/PHPCI/Application.php:88, referer: http://phpci.adstats01.domain.com/project/view/1
[Thu Apr 02 15:48:08.640090 2015] [:error] [pid 19630] [client 10.28.1.35:58381] PHP   4. b8\\Application->getController() /var/www/phpci/vendor/block8/b8framework/b8/Application.php:69, referer: http://phpci.adstats01.domain.com/project/view/1
[Thu Apr 02 15:48:08.640136 2015] [:error] [pid 19630] [client 10.28.1.35:58381] PHP   5. PHPCI\\Application->loadController() /var/www/phpci/vendor/block8/b8framework/b8/Application.php:85, referer: http://phpci.adstats01.domain.com/project/view/1
[Thu Apr 02 15:48:08.640179 2015] [:error] [pid 19630] [client 10.28.1.35:58381] PHP   6. b8\\Application->loadController() /var/www/phpci/PHPCI/Application.php:124, referer: http://phpci.adstats01.domain.com/project/view/1

**Comment by agarzon** [comment]
I'm facing the same issue. Last version, fresh installation, Apache.
