### ISSUE TITLE
phpci does not work after installation

### ISSUE THREAD

**Issue by barbos3000** [Block8/PHPCI#226]
When trying to install phpci according to https://github.com/Block8/PHPCI/wiki/Installing-PHPCI and calling the Application from my browser I am redirected from https://...../phpci to https://...../phpci/session/login

Also included the mod_rewrite lines within an .htaccess and put it into my apache configuration (+restart). Does not make any difference

**Comment by lakshmi28gsrl** [comment]
I didnot get any solution for this by writting coding in htaccess, AllowOverwrite ALL, mod_rewrite enable but iam still having same issue how can I solve this. Please help me.

**Comment by lakshmi28gsrl** [comment]
I didnot get any solution for this by writting coding in htaccess, AllowOverwrite ALL, mod_rewrite enable but iam still having same issue how can I solve this. Please help me.

**Comment by dancryer** [comment]
@lakshmi28gsrl Please don't re-post the same comment in several places, it just makes it harder for us to help you. 

Please can you provide the following information:

1. When you go to http://localhost/PHPCI/session/login - Where do you get redirected to?
2. What do you have in your .htaccess file?

**Comment by lakshmi28gsrl** [comment]
Hi,
sorry for reposting. 
1. Iam getting 404 error.
2.In htaccess I have 

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.php [L]
</IfModule>

**Comment by dancryer** [comment]
Try changing `RewriteBase /` to `RewriteBase /PHPCI/`

I'm not very good with Apache, so not sure whether that's the right bit to change... but PHPCI isn't in /, so it makes sense that you'd base rewrites off its actual location.

**Comment by lakshmi28gsrl** [comment]
yes I tried it just like PHPCI is in my c:/xampp/htdocs/PHPCI

I tried with in all ways but iam unable to find solution

1. RewriteBase /PHPCI/
2. RewriteBase /xampp/htdocs/PHPCI/
3. RewriteBase /htdocs/PHPCI/
4.  RewriteBase /PHPCI/public

and all other possiblities but iam getting same 404 page. Can you help me

**Comment by lakshmi28gsrl** [comment]
Hi,
Iam getting an error screen when accessing http://localhost/phpci/session/login.I have installed PHPCI in windows. Please find the error screen. Can you please help me in solving these error where has I went wrong
![error](https://cloud.githubusercontent.com/assets/11456730/6666051/71bc40ba-cc06-11e4-813c-0fa7e2f3ea2e.png)

**Comment by lakshmi28gsrl** [comment]
Hi,

can any one help me regarding this.

**Comment by beryllium** [comment]
I encountered this issue today. The quickest way to get it resolved was to run `a2enmod rewrite`, make sure I copied the `.htaccess.dist` to `.htaccess` in the public folder, and then run `service apache2 restart`. This will probably require making sure the Apache configuration isn't set to "AllowOverride None".

**Comment by XMMM1** [comment]
Hey all,
i have one small question for help. I try to install PHPCI on nginx on raspberry, but this is my first try using nginx and i am facing some issues. I install phpmyadmin and some other stuff with success and all worked as expected. But i have some difficulties configure phpci virtualhost. So i browse majority of forums where subject pf installing phpci is discussed, but for now without success.

So my problems are: on accessing page on xxx.xxx.xxx.xxx/phpci/public i have redirect loop to index.html also i get 500 error loading public link and app icon. I get by this issue if i set direct server_name to ip and not some name; but in this case i get controller not found error. 

So i try some different virtual host configurations but with no success. So can please someone assist me with right configuration? (I also try smyphony's and @johnatannvmd - listed upper but still with no success). What am i missing? Which right's do i need to set to phpci folder?

Current i have this virtual host:
```
raspberry pi 2
root folder of project /usr/share/nginx/www/phpci
phpci permission and group root:root

upstream php {
        #server 127.0.0.1:9000;
        server unix:/var/run/php5-fpm.sock; #for PHP-FPM running on UNIX socket
    }
server {
        listen 81;
        root /usr/share/nginx/www/phpci/public;
        server_name localhost;
        
location / {
        index index.php;
        try_files $uri @rewriteapp;
    }

    location @rewriteapp {
        rewrite ^(.*)$ /index.php/$1 last;
    }

    # pass the PHP scripts to FastCGI server from upstream phpfcgi
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param  HTTPS off;
    }
}
```

**Comment by Adirelle** [comment]
This configuration works on Debian Wheezy with nginx and php5-fpm, serving from /srv/phpci instead of /var/www/phpci, but that shouldn't matter.

```nginx
server {
        root /srv/phpci/public;

        server_name localhost;

        location / {
                # try to serve file directly, fallback to index.php
                try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param HTTPS off;
                # Prevents URIs that include the front controller. This will 404: http://domain.tld/app.php/some-path
                # Remove the internal directive to allow URIs like this
                internal;
        }
}
```

**Comment by mpeshev** [comment]
Unlike @raistlin I had to use a slightly different setup in order to make it work, my vhost setup looks like that:

    <VirtualHost *:80>
        ServerName  {mydomainhere}
        DocumentRoot    /var/www/html/phpci/public

        <Directory /var/www/html/>
                Options Indexes FollowSymlinks MultiViews
                RewriteEngine On
                AllowOverride All
                Order allow,deny
                Allow from All
                  RewriteBase /
                  RewriteCond %{REQUEST_FILENAME} !-f
                  RewriteCond %{REQUEST_FILENAME} !-d
                  RewriteRule ^(.*)$ /index.php/$1 [L]
        </Directory>
    </VirtualHost>

This includes the .htaccess rules as well since despite of the override, they didn't work out. The directory defined is the root directory of phpci, otherwise it does require index.php in the URL regardless.

**Comment by rickhub** [comment]
Simply renamed `.htaccess.dist` to `.htaccess` in the `/public` folder to fix this.

**Comment by okdewit** [comment]
To those who still encounter weird redirection problems after making sure virtualhost, rewrite & htaccess have been configured correctly:

Be sure the phpci URL in PHPCI/config.yml has been set correctly. You set this URL during the `./console phpci:install` step, but if it's not actually corresponding to the publicly accessible URL of your installation, it won't redirect properly.

In my case, I had `https://domain.com/phpci` in the config.yml, but had set my virtualhost documentroot to /var/www/phpci/public, causing the first request to index.php to be redirected to /phpci/session/login instead of /session/login.

**Comment by chenster** [comment]
Here's the httpd-vhosts.conf that worked for me:

```
<VirtualHost *:80>
 ServerAdmin xxxxxx@gmail.com
 DocumentRoot "/www/phpci/public"
 ServerName phpci.local
 ServerAlias *.phpci.local
 ErrorLog "/private/var/log/apache2/phpci.error_log"
 CustomLog "/private/var/log/apache2/phpci.access_log" common
<Directory "/www/phpci/public">
Options Indexes FollowSymLinks MultiViews
Order allow,deny
Allow from all
AllowOverride All
Require all granted
Satisfy Any
</Directory>
</VirtualHost>
```

In hosts, remember to add

`127.0.0.1       phpci.local`

**Comment by Brazers** [comment]
For those who don't want/ or can not set the virtual host, the .htaccess file should include

`<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /somename/PHPCI/phpci/public/index.php [L]
</IfModule>
`

so add the full path

**Comment by COil** [comment]
The issue for me was using a symlink in the Apache vhost, it works now.
