### ISSUE TITLE
Question about vendors, include path

### ISSUE THREAD

**Issue by maks-rafalko** [Block8/PHPCI#231]
Hi,

If I use PHPCI for Symfony2 project with Behat/Mink tests, what is the best way to use vendors from project directory (PHPCI_PATH/../prejectX-buildX/vendor)?

As I understand, PHPCI's `composer.json` should not contain any behat packages and PHPCI should use `vendors` from the build folder, but build fails with fatal error `PHP Fatal error:  require(): Failed opening required 'Behat\Symfony2Extension\Extension'`

When I installed behat extensions in PHPCI's `composer.json` file - build is successfull.
But I'm sure it is a bad way - vendors should be only in the project, not in PHPCI. 

PS: Don't know why, but `set_include_path(%build_forler/vendor%)` doesn't help.

**Comment by maximal** [comment]
+1 to @borNfreee
