### ISSUE TITLE
Git Clone with references / cache

### ISSUE THREAD

**Issue by adamlc** [Block8/PHPCI#302]
It looks the repository is cloned from a fresh each time a test is run. This can be speeded up dramatically by caching the repository locally.

Try reading this website for more info:

http://randyfay.com/content/reference-cache-repositories-speed-clones-git-clone-reference

**Comment by thinkspill** [comment]
+1 :D

**Comment by Spiritvn** [comment]
Sorry for reopen this, how we do config for this to work?

**Comment by thinkspill** [comment]
```
build_settings:
    clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
```

See top of the page here: https://www.phptesting.org/wiki/Adding-PHPCI-Support-to-Your-Projects

**Comment by Spiritvn** [comment]
Thanks @thinkspill, i dont really understand the clone_depth setting because when i tried, it still clone the entire repo on every build?

I really need it only build the changes, not clone...

**Comment by REBELinBLUE** [comment]
`clone_depth` uses the `--depth` parameter in `git clone` it makes a shallow clone, so the cloned copy won't have any history just `HEAD`. There is no way to pull in just the files which have changed, and I'm not sure that would be desirable anyway as then things like unit tests would almost certainly fail?

**Comment by Spiritvn** [comment]
@REBELinBLUE thanks, ad yes that's why i asked for the config to make the commit https://github.com/Block8/PHPCI/pull/838 to work. It's ok to build the new one to test but shouldn't clone entire source, for big project it would be so long on that part.

I just didn't notice that it was closed instead of merged as you did... ^^
