### ISSUE TITLE
Could not find Composer.

### ISSUE THREAD

**Issue by sobit** [Block8/PHPCI#303]
I have composer installed globally on my system. It is accessible from apache user as well, i.e. when I run `which composer` I get `/usr/local/bin/composer`.

However, running the build fails with the error `Could not find Composer.`. Any ideas?

**Comment by Stefaminator** [comment]
Sorry guys but i think this issue has not been resolved!
I don't know how to reopen it.

Same configuration for me: installed composer in /usr/local/bin and i got the error "composer can not be found" 

@oRastor adding the following line in crontab results in many more not-found-errors than before:
PATH=/usr/local/bin

**Comment by mgdigital** [comment]
I've arrived on this page after experiencing the same problem, but have found a better workaround. Assuming composer is already installed globally to /usr/local/bin/composer, you can just make a symbolic link to /usr/bin/composer allowing it to be found by the cron job:

`ln -s /usr/local/bin/composer /usr/bin/composer`

**Comment by mertoksuz** [comment]
@oRastor

Thank you, solved my problem.

I used like this;
```
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
```
