### ISSUE TITLE
Fresh Installation - 404 Error

### ISSUE THREAD

**Issue by mikebronner** [Block8/PHPCI#316]
I'm getting this after a fresh installation when browsing to http://localhost (it redirects to session/login):

```
Not Found

The requested URL /session/login was not found on this server.
Apache/2.4.7 (Ubuntu) Server at localhost Port 80
```

Any thoughts on how to solve this?

**Comment by murrion** [comment]
I had this issue and a combination of 3 things solved it:

1. ensure to enable mod_rewrite in Apache
2. Update your Virtual host to include "AllowOverride FileInfo"
3. In /public, rename .htaccess.dist to .htaccess

**Comment by mavimo** [comment]
@murrion @mikebronner can you update the installation wiki page? Thanks!

**Comment by tvbeek** [comment]
Step 1 and 3 are already mentoined in [Apache Example (require mod_rewrite installed)](https://github.com/Block8/PHPCI/wiki/Installing-PHPCI#apache-example-require-mod_rewrite-installed)

Or am I wrong?
