### ISSUE TITLE
Feature: Move build to directory with exclusion 

### ISSUE THREAD

**Issue by confact** [Block8/PHPCI#366]
I want to move my successful build to a directory (for a easy local deployment) But i want to exclude phpunit and config directory.

rsync works:

```
rsync -av --progress sourcefolder /destinationfolder --exclude thefoldertoexclude
```

or find:

```
find . -type f -not -path '*/not-from-here/*' -exec cp '{}' '/dest/{}' \;
```

Best thing would be to be able to exclude multiplied paths.

Is this possible to add to the movebuild plugin?

**Comment by Rhymond** [comment]
It includes build number, how to ignore it?
