### ISSUE TITLE
Add support for Github's application/json webhook option

### ISSUE THREAD

**Issue by jimmycleuren** [Block8/PHPCI#374]
When a new build starts, the following function is executed:

$this->build->sendStatusPostback();

However, there is an error in the b8\HttpClient class and the build fails immediately.

Warning: json_decode() expects parameter 1 to be string, array given in /var/www/tools/PHPCI/vendor/block8/b8framework/b8/HttpClient.php line 88

The error happens on the following line:
$res['body']      = json_decode($res['body'], true);

Maybe it's best to check if $res['body'] is an array before calling json_decode on it ?

**Comment by dancryer** [comment]
Support for the JSON request type was implemented a couple of releases ago. :)
