### ISSUE TITLE
adding a project causes openssh dialog in buildin webserver

### ISSUE THREAD

**Issue by ppetermann** [Block8/PHPCI#407]
whenever i click on "add project", i can see the php - buildin webserver asking me on the very same window that the webserver is running on:

Enter file in which to save the key (/home/ppetermann/.ssh/id_rsa):

now a) i usually don't want to create a new key and b) it should'nt try to install that as a key of the user thats running the webserver.

**Comment by dancryer** [comment]
I think this should be fixed with our latest changes to the SSH key generation. Please feel free to reopen if that is not the case.
