### ISSUE TITLE
Multiple branch build

### ISSUE THREAD

**Issue by kix** [Block8/PHPCI#413]
Is this possible? I've looked through the doc and the open issues and couldn't find anything on this subject.
What's expected: I should be able to specify multiple branches to build from. If multiple developers are doing their stuff in feature branches, a push to any of these branches should trigger a build. Then, all the specified branches are merged into a temporary local branch, and then build should assert that these branches merge cleanly. If they do, then we can run the usual checks, like CS, tests, whatnot.

**Comment by gansky-alexander** [comment]
hello, everyone. Can anybody tell about that issue, does phpci have that functionality? if no, when it can be done if it possible?

**Comment by tvbeek** [comment]
It doesn't have this and on this moment there isn't any active plan to add it. But feel free to create a pr to add it
