### ISSUE TITLE
Builds failing with cryptic message

### ISSUE THREAD

**Issue by cooperaj** [Block8/PHPCI#461]
I've got a bitbucket POST hooks setup so that my builds are automated. Of late any build that comes in via that (as opposed to a manual one) fails and all that ends up in the log box is:

```
Failed to clone remote git repository.
Exception: Could not create a working copy.
```

Running the build manually causes it to succeed. 

I'm unable to find any further log information.

**Comment by dancryer** [comment]
@cooperaj @sklerotraficon I assume you have managed to fix this (and/or it has been fixed in a subsequent release) ?
