### ISSUE TITLE
Integrate support for web-puc

### ISSUE THREAD

**Issue by fulldecent** [Block8/PHPCI#516]
It provides validation of web projects to ensure use of latest available CSS & JS includes

At: https://github.com/fulldecent/web-puc

**Comment by ilyalyo** [comment]
Added PR https://github.com/Block8/PHPCI/pull/1254

**Comment by fulldecent** [comment]
This looks good

**Comment by fulldecent** [comment]
Bump

**Comment by fulldecent** [comment]
Closing issue, PR closed
