### ISSUE TITLE
Email plugin - Connection could not be established with host localhost

### ISSUE THREAD

**Issue by jbrooksuk** [Block8/PHPCI#523]
```
RUNNING PLUGIN: email
EXCEPTION: Connection could not be established with host localhost [Connection refused #111]
PLUGIN STATUS: FAILED
```

I've setup my SMTP settings using Mandrill, so why is it still using `localhost`?

**Comment by dancryer** [comment]
Closing this on the assumption it is fixed and/or no longer relevant by now. Feel free to reopen if this assumption is incorrect.
