### ISSUE TITLE
"Build started" always null

### ISSUE THREAD

**Issue by AlexDubstone** [Block8/PHPCI#545]
Hello,

I know this problem has been posted before, but although I tried the possible solutions that were posted I still can't figure out why phpci is not building the project for me. And aparently there is no log file that's telling what is going wrong.

What I did so far:
- installed phpci, that was really easy and well explained
- set up  a gitlab project
- add the webhook url to the gitlab project
- add phpci.yml to the project

The webhook is working. I see a new build-attempt  with the right commit reference. However, it just keeps staying in "pending" and is not doing anything else.

I then tried:
- change owner of the whole phpci folder to root for testing purposes
- verify that `shell_exec` and `exec` are available (although i think the installer is already doing that)
- create a smaller testproject (to make sure it's not composer that is hanging)
-  change the project location from gitlab to github

And a few more things that I just tried because I started to become desperate...but they did not really make sense.
The project I'm trying to build is https://github.com/AlexDubstone/codeceptci

Is there anything else I could try? I'd really really appreciate any help.

Thank you very much
Alex

**Comment by Patabugen** [comment]
This caught me for a while after I setup PHPCI, a number 8 to the list on this page would have resolved the issue for me:

https://www.phptesting.org/install-phpci

`#8. Setup Cron or Daemon to run tests`

It should also be added to "Standard installation process:" on this page, which actually contains the instructions but they're lost below all the web-server configurations.

https://www.phptesting.org/wiki/Installing-PHPCI

**Comment by mikebronner** [comment]
Thanks, @Patabugen ! Added your a bullet point as per your suggestion. :)

**Comment by marclaporte** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  marc@laporte.name
    Domain marclaporte.com has exceeded the max emails per hour (311/300 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:7491)
	by uskm12.fastbighost.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.84)
	(envelope-from <bounces+848413-0bd8-marc=marclaporte.com@sgmail.github.com>)
	id 1YKrcM-002RNZ-HD
	for marc@marclaporte.com; Mon, 09 Feb 2015 18:55:27 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=xruqFEf7Cqf7XDyo0XKHiZ+7abo=; b=XoubEnJMIfG1xsl4
	Bee+SkLs2d42CWW4gK4KO6A9acCcaJ0zsqW+Rbuduk3J45R+8N4el8aaKSE3p+tp
	FXRruHUx3cg6kN5tHtQdpL76lTUCKHjA0ETVyaOY3OM0tNO2lAF+kFoJduR9IYlT
	qmKsVuqmPcXpprtGPS05iF2oJwk=
Received: by filter0200p1mdw1.sendgrid.net with SMTP id filter0200p1mdw1.21591.54D8E67313
        2015-02-09 16:55:17.757418389 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd-020 (SG) with ESMTP id 14b6f4436c4.564c.273187
	for <marc@marclaporte.com>; Mon, 09 Feb 2015 16:55:16 +0000 (UTC)
Date: Mon, 09 Feb 2015 08:55:16 -0800

**Comment by geoidesic** [comment]
This also caught me out.
I think you can improve the docs by stating in parenthesis that `(this step is not optional, you must have either the cronjob or the daemon running or you won't be able to build)`
