### ISSUE TITLE
Running acceptance tests with codeception

### ISSUE THREAD

**Issue by AlexDubstone** [Block8/PHPCI#546]
PHPCI is running and building fine now, however I still don't know how to do acceptance testing with Codeception. The codeception plugin says it "Enables full acceptance, unit, and functional testing.". However, I don't know how to set up the codeception.yml / acceptance.suite.yml.

For acceptance testing (and API testing) I need a web-path for the project. Is there anything I can do with PHPCI at the moment? Has anyone already successfully set up acceptance testing?

Regards
Alex

**Comment by tvbeek** [comment]
You need to run a server (what phpci doesn't do for your test)
I have explain two ways in #743
