### ISSUE TITLE
PHP path with spaces

### ISSUE THREAD

**Issue by potapczuk** [Block8/PHPCI#548]
If my PHP executable has spaces in its path there will be a lot of errors

**Comment by tvbeek** [comment]
I think it's the same problem as #698 and @potapczuk didn't give any reply so I close this one

**Comment by marclaporte** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  marc@laporte.name
    Domain marclaporte.com has exceeded the max emails per hour (306/300 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:49220 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by uskm12.fastbighost.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.84)
	(envelope-from <noreply@github.com>)
	id 1YKrbt-002P9P-D6
	for marc@marclaporte.com; Mon, 09 Feb 2015 18:54:57 +0200
Date: Mon, 09 Feb 2015 08:54:50 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1423500890;
	bh=MufQtbgD7sRPnQxp1/sAtfC4APXxa/f6Fif4Zh9wi0c=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=yuIPVrwhn47nkOs6XBxUA6ElSS/fYe+WZ/wJU8iw8aVZfW+nQ50qIw9unhdu5h/94
	 3AjJTqo4icuk3hNn7ckMkNMb7tOEjx0yNbp+BAs3W02VWNjVPlkm560hQmbvSbsEJN
	 BjZOWsOZV0DE/CnUqe0AzU7YWOJPfERDpmwqBJsU=

**Comment by marclaporte** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  marc@laporte.name
    Domain marclaporte.com has exceeded the max emails per hour (307/300 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:50334 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by uskm12.fastbighost.net with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.84)
	(envelope-from <noreply@github.com>)
	id 1YKrbt-002P9S-JA
	for marc@marclaporte.com; Mon, 09 Feb 2015 18:54:58 +0200
Date: Mon, 09 Feb 2015 08:54:50 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1423500890;
	bh=uIvpOGKEKZI41GI0ir9Uf4Ny1ib5IRWXx8rd+RWl9YA=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=kus1BkkgLpQo/y3ngsulFBh9NuipQSOJOCNjqV/LhjixK4y8Ls4+b3xdzkQtoE+4U
	 oWJso/2mbGUDfSWOwtKFhZK9ZacZhm55WoqErleOG7iHPoSUWXKnNGGZolokwOvmRm
	 U9c//4JYKIfx/5Pw/e2dv22WoTLXdab/GeLPrSZ0=
