### ISSUE TITLE
RUNNING PLUGIN: php_code_sniffer / PLUGIN STATUS: FAILED

### ISSUE THREAD

**Issue by designvoid** [Block8/PHPCI#551]
I am working on a mac running Mamp Pro and...

I have seemingly got everything set up but have run into a few issues, firstly adding the PHPCodeSniffer plugin - everytime I ran Composer Update it errored, so I modified the composer.json to require dev and changed the phpcs version to '1.*' and that seemed to work but now when I run a build I just get:

```
Working copy created: /
RUNNING PLUGIN: composer
Using --prefer-source flag
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Removing composer/installers (v1.0.8)
  - Installing composer/installers (v1.0.9)
    Loading from cache
  - Removing mjohnson/uploader (4.5.1)
  - Installing mjohnson/uploader (4.5.2)
    Loading from cache
Generating autoload files
PLUGIN STATUS: SUCCESS!
RUNNING PLUGIN: php_code_sniffer
PLUGIN STATUS: FAILED
BUILD FAILURE
Removing build.
```

Any suggestions?

**Comment by allaniftrue** [comment]
How did you fix it?
