### ISSUE TITLE
github pull request build

### ISSUE THREAD

**Issue by Stricted** [Block8/PHPCI#559]
hello
i try to test build pull requests on a private repo and have the problem that the clone_url is https://github.com/user/repo
on private repos that is not working here we need the ssh_url to clone and that is not supported

can you please add support for private repositorys?

**Comment by MartinSadovy** [comment]
Guys, please could you test https://github.com/Block8/PHPCI/pull/832

**Comment by mikebronner** [comment]
This should be fixed now. Closing. (Please re-open if you still are experiencing this issue.)
