### ISSUE TITLE
MySQL install error

### ISSUE THREAD

**Issue by etki** [Block8/PHPCI#578]
Hi.
Looks like there is some trouble with migrations: when i've tried to install PHPCI, installation process dropped out on admin user creation with error 42S02 (Base table or view doesn't exist blah-blah **Table 'ci_php.user' doesn't exist**). When i've inspected database contents, there was nothing but empty migrations table; `./console phpci:update` didn't help as well.

**Comment by tvbeek** [comment]
Do I understand it good that the change in the installation guide has fix this problem and this issue can be closed?

**Comment by etki** [comment]
@tvbeek well, i was following guide when i've met this error, but it is certain that i can't recreate original error conditions, so i guess it would be better to just close this issue. I'll open new one if i'll face this error again.
