### ISSUE TITLE
Subversion support

### ISSUE THREAD

**Issue by amacgregor** [Block8/PHPCI#609]
Is there are any plans to allow Subversion has an alternative to Git? I'm unfortunately stuck with Subversion for the time being. 

If there is no plans for supporting subversion I would like to try and integrate it, any possible issues that anyone can think about ?

Cheers!

**Comment by jdunmore** [comment]
@amacgregor did you get this solved? I'm happy to help if you haven't yet done this. Thanks.

**Comment by dancryer** [comment]
@jdunmore We added SVN support in v1.6 (released today): https://github.com/Block8/PHPCI/blob/master/PHPCI/Model/Build/SubversionBuild.php
