### ISSUE TITLE
php_parallel_lint notice error.

### ISSUE THREAD

**Issue by huglester** [Block8/PHPCI#664]
Hello,

when using this `php_parallel_lint`, I get error like this:

```php
RUNNING PLUGIN: php_parallel_lint
EXCEPTION: Notice: Array to string conversion in /var/www/PHPCI/Helper/BaseCommandExecutor.php line 75
PLUGIN STATUS: FAILED
```

Thanks

**Comment by sebastian-berc** [comment]
I had same issue today, and this change will help you:
```
    php_parallel_lint:
        directory: 
            - "app"
```
to:
```
    php_parallel_lint:
        directory: "app"
```

**Comment by Caffe1neAdd1ct** [comment]
Just had the same issue, ended up changing to:

```
    php_parallel_lint:
        ignore:
            - "database"
            - "logs"
            - "vendor"
```

Would have been nicer to whitelist:

```
    php_parallel_lint:
        directory:
            - "application"
            - "public"
```

Would be possible if php parallel lint support `--include` as well as `--exclude` (need to check it may not have an include flag available).

**Comment by dancryer** [comment]
Closing this on the assumption it is fixed and/or no longer relevant by now. Feel free to reopen if this assumption is incorrect.
