### ISSUE TITLE
Your email address: root@localhost  Must be a valid email address.

### ISSUE THREAD

**Issue by flowl** [Block8/PHPCI#670]
Your email address: root@localhost
    Must be a valid email address.

`root@localhost` **is** a valid address.

**Comment by SamMousa** [comment]
PHPCI uses php built-in validation: http://php.net/manual/en/filter.filters.validate.php
So this should be reported to https://bugs.php.net/.

**Comment by flowl** [comment]
@SamMousa  Thanks for your feedback. You are right and there also is already a bugreport: https://bugs.php.net/bug.php?id=66553 
I think this can be closed, thanks
