### ISSUE TITLE
Unprotected private key file when running builds

### ISSUE THREAD

**Issue by bensinclair** [Block8/PHPCI#671]
I have installed and set up PHPCI on a Vagrant box running Ubuntu 12.04. I added my project, copied the deploy key to Bitbucket and configured my git repo with my phpci.yml file.

Every time it runs a new build, I get this error:

```
Cloning into '/var/www/phpci/PHPCI/build/project1-build3'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0777 for '/var/www/phpci/PHPCI/build/project2-build10.key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
bad permissions: ignore key: /var/www/phpci/PHPCI/build/project2-build10.key
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

Failed to clone remote git repository.
Exception: Could not create a working copy.
```

Heres the command line output:

```
$ ./console phpci:run-builds
[2014-12-01 08:51:03] RunCommand.INFO: Finding builds to process [] []

[2014-12-01 08:51:03] RunCommand.INFO: Found 1 builds [] []

[2014-12-01 08:51:03] RunCommand.ERROR: Exception: Warning: file_put_contents(/var/www/phpci/PHPCI/build/project1-build3.key): failed to open stream: Operation not permitted in /var/www/phpci/PHPCI/Model/Build/RemoteGitBuild.php line 147 {"buildID":"3"} []
```

It seems as thought the CHMOD isn't being applied to the file. Here's some lines around `147` in `/var/www/phpci/PHPCI/Model/Build/RemoteGitBuild.php`

```
// Write the contents of this project's git key to the file:
file_put_contents($keyFile, $this->getProject()->getSshPrivateKey());
chmod($keyFile, 0600);
```

I tried changing it to `0400` to no avail.

Any ideas what I might need to do to get this running?

**Comment by SamMousa** [comment]
Regardless of the source of issue, shouldn't that chmod return value be checked. Seems quite simply to throw an exception if chmod fails, that way at least the user gets a clearer error message.

**Comment by kentpachi** [comment]
same problem here

**Comment by kentpachi** [comment]
solver by adding sudo to phpci:run-builds

**Comment by davidnuon** [comment]
Same here. I'm running builds as a cron job. I don't encounter the problem if I run it as root.

**Comment by dancryer** [comment]
Closing this on the assumption it is fixed and/or no longer relevant by now. Feel free to reopen if this assumption is incorrect.
