### ISSUE TITLE
Runcommand in infinite loop

### ISSUE THREAD

**Issue by jimmycleuren** [Block8/PHPCI#684]
My builds are starting with the runcommand entry in the crontab:

  *     *    *   *   *     /usr/bin/php /var/www/tools/PHPCI/console phpci:run-builds

However, since the last update, it gets stuk in a loop printing the same log line over and over again:

[2014-12-05 22:31:39] RunCommand.INFO: Skipping Build #918 - Project build already in progress. [] []

**Comment by dancryer** [comment]
Closing this on the assumption it is fixed and/or no longer relevant by now. Feel free to reopen if this assumption is incorrect.
