### ISSUE TITLE
PhpMessDetector unable to parse services.xml

### ISSUE THREAD

**Issue by spyworldxp** [Block8/PHPCI#693]
RUNNING PLUGIN: \PHPCI\Plugin\PhpMessDetector
Unable to parse file "/var/www/phpci/vendor/pdepend/pdepend/src/main/php/PDepend/DependencyInjection/../../../resources/services.xml".

EXCEPTION: Warning: simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found in /var/www/phpci/PHPCI/Plugin/PhpMessDetector.php line 129
PLUGIN STATUS: FAILED
BUILD FAILURE

**Comment by dancryer** [comment]
Closing this on the assumption it is fixed and/or no longer relevant by now. Feel free to reopen if this assumption is incorrect.
