### ISSUE TITLE
[Proposal] Technical Debt Checker

### ISSUE THREAD

**Issue by jfi** [Block8/PHPCI#715]
Write a plugin which will look for strings (user-configurable) in your code such as "TODO", "FIXME".

(I have some work on this done at the moment, it just needs finishing off then I'll make a PR)

**Comment by dag-io** [comment]
Could be nice to evaluate the debt (amount of time to fix) based on the amount of issues and the complexity to fix each of them.

**Comment by wandersonwhcr** [comment]
@dag-io any suggestions of how can we do it?

I can just imagine a counter.

```
plugin:
    TODO: 10
    FIXME: 15
    @deprecated: 8
```

**Comment by dag-io** [comment]
@wandersonwhcr I was talking about technical debt based on issues reported by already existing (phpmd, phpcs, etc).

I thing todo and fixme should not be in the code but in your project tracking tools (Jira, Github, etc).

**Comment by wandersonwhcr** [comment]
@dag-io hum, OK.

Can you explain more about that? Must we create another issue to talk about it?

**Comment by dag-io** [comment]
@wandersonwhcr Yes maybe to avoid to mess with @jfi original idea

**Comment by wandersonwhcr** [comment]
:+1:

**Comment by jfi** [comment]
Just an update here - unix support is working but it's proving a bit of a struggle to get it working for systems where 'grep' isn't available. Does anyone have a Windows machine and wouldn't mind helping test a few things?

**Comment by jfi** [comment]
I now have this working cross-platform. Merged in 8f5d855193e6b67cd042ac61c8d9553359d6b8d5.
