### ISSUE TITLE
Date localization

### ISSUE THREAD

**Issue by Adirelle** [Block8/PHPCI#732]
Even though the front-end uses the right language, most dates are still in English format (field ordering, AM/PM).

I would like to submit a request, but I am not sure how to fix this:
* for PHP-rendered dates, could we use a PHP module, like the intl module ? (see http://php.net/manual/fr/class.intldateformatter.php) or use built-in code ?
* for the moment.js-rendered dates, I guess `moment.locale(currentLang);` should be added somewhere in the page initialization.

Any answer ?

**Comment by mavimo** [comment]
:+1: to move date on DOM using <time> tag with data attribute (eg: ```<time datetime="2015-01-08T16:40:47Z" >```) and convert date on frontend using moment.js like github & c.

**Comment by Adirelle** [comment]
It seems daterangepicker embeds moment.js 2.1.0, while moment.js 2.8.4 is also loaded from the layouthtml. So far, I think the 2.1.0 version is "winning", which is causing issues.
