### ISSUE TITLE
Configuration from UI

### ISSUE THREAD

**Issue by x00xer** [Block8/PHPCI#740]
Do you know how to achieve what is mentioned here 

http://youtu.be/ueYrUhfI4YA?t=8m24s

???

I've searched everywhere and I can't find it out :( am I missing something ? or misunderstood speaker ?

Thanks.

**Comment by ViGo5190** [comment]
@x00xer You understand right. In edit project interface you have specific input for this. Upper the branch selector. You just can type config in this input.

**Comment by x00xer** [comment]
@ViGo5190  Oh I see, it's just input field for configuration file content, ok :-) it's not what I understood from video. I thought there is UI to configure plugin settings.

**Comment by tvbeek** [comment]
@x00xer If I read the last comment I think this issue can be closed, is that true?
