### ISSUE TITLE
Pre-Requisites problem

### ISSUE THREAD

**Issue by somewhereocean** [Block8/PHPCI#741]
https://www.phptesting.org/install-phpci

PHPCI/Application.php Line:50
$skipAuth = [$this, 'shouldSkipAuth'];

you need php version 5.4 up

**Comment by murrion** [comment]
Confirmed here, Can't run PHPCI on PHP 5.3.10. Upgrading to PHP 5.4.36 allowed me to go further.

**Comment by dancryer** [comment]
We've committed to supporting PHP 5.3 for now, so actually we need to fix that bit of code rather than update the prerequisites. :)

**Comment by somewhereocean** [comment]
That's great, thank you. ;)
