### ISSUE TITLE
Field 'status' doesn't have a default value when click "Rebuild Now"

### ISSUE THREAD

**Issue by corretge** [Block8/PHPCI#746]
When I click on "Rebuild Now" I get this message:

    SQLSTATE[HY000]: General error: 1364 Field 'status' doesn't have a default value

The MySQL server is:

    Server version: 5.6.20-log MySQL Community Server (GPL)

**Comment by dansoap** [comment]
I also fixed this in PR #725

**Comment by dancryer** [comment]
This is fixed in @dansoap's PR above.
