### ISSUE TITLE
Ability to add project to archive

### ISSUE THREAD

**Issue by zviryatko** [Block8/PHPCI#762]
Hi,
my team has a new project nearly every two week, so we have many-many project and projects list in main screen is big, so is there any such functionality in the plans for the future?

I think that it is better to sort projects since the last build and hide archived project from main projects list (but show it in right side if project has new commit, for gitlab hooks).

I will try implement this feature, so write your suggestions.

**Comment by tvbeek** [comment]
I like the idea.
I think it is good to have the option to sort on last date (but not to replace the sort on name)
And an option to archive the project so it is hidden from the main page. (It need to have a filter or separated page with archived projects to set it back)

**Comment by maschmann** [comment]
:+1:
