### ISSUE TITLE
phpdoccheck on ubuntu 14.04

### ISSUE THREAD

**Issue by danbuntu** [Block8/PHPCI#776]
Hi

I have PHPCI installed on ubuntu 14.04 I've managed to gert all the plugins I want working apart from phpdoccheck. I've installed it via the pear channel but I get the error:

RUNNING PLUGIN: \PHPCI\Plugin\PhpDocblockChecker
Could not find phpdoccheck

Is someone able to point me in the right direction please

**Comment by dancryer** [comment]
Please can you paste a copy of your PHPCI composer.json file here?

**Comment by danbuntu** [comment]
here it is in all it's glory:


{
    "name": "block8\/phpci",
    "description": "Simple continuous integration for PHP projects.",
    "minimum-stability": "stable",
    "type": "library",
    "keywords": [
        "php",
        "phpci",
        "ci",
        "continuous",
        "integration",
        "testing",
        "phpunit",
        "continuous integration",
        "jenkins",
        "travis"
    ],
    "homepage": "http:\/\/www.phptesting.org\/",
    "license": "BSD-2-Clause",
    "authors": [
        {
            "name": "Dan Cryer",
            "email": "dan.cryer@block8.co.uk",
            "homepage": "http:\/\/www.block8.co.uk",
            "role": "Developer"
        }
    ],
    "support": {
        "email": "hello+phpci@block8.co.uk",
        "issues": "https:\/\/github.com\/Block8\/PHPCI\/issues",
        "source": "https:\/\/github.com\/Block8\/PHPCI"
    },
    "autoload": {
        "psr-4": {
            "PHPCI\\": "PHPCI"
        }
    },
    "require": {
        "php": ">=5.3.8",
        "ext-pdo": "*",
        "ext-pdo_mysql": "*",
        "block8\/b8framework": "~1.0",
        "ircmaxell\/password-compat": "~1.0",
        "swiftmailer\/swiftmailer": "~5.0",
        "symfony\/yaml": "~2.1",
        "symfony\/console": "~2.1",
        "psr\/log": "~1.0",
        "monolog\/monolog": "~1.6",
        "pimple\/pimple": "~1.1",
        "robmorgan\/phinx": "~0.3",
        "phpmd\/phpmd": "2.2.0",
        "squizlabs\/php_codesniffer": "2.2.0",
        "sebastian\/phpcpd": "2.0.1",
        "phploc\/phploc": "2.0.6"
    },
    "require-dev": {
        "phpunit\/phpunit": "~4.0",
        "phpspec\/prophecy-phpunit": "~1.0",
        "phpmd\/phpmd": "~2.0",
        "squizlabs\/php_codesniffer": "~1.5",
        "block8\/php-docblock-checker": "~1.0",
        "phploc\/phploc": "~2.0"
    },
    "suggest": {
        "block8\/php-docblock-checker": "PHP Docblock Checker",
        "phpmd\/phpmd": "PHP Mess Detector",
        "sebastian\/phpcpd": "PHP Copy\/Paste Detector",
        "squizlabs\/php_codesniffer": "PHP Code Sniffer",
        "phpspec\/phpspec": "PHP Spec",
        "fabpot\/php-cs-fixer": "PHP Code Sniffer Fixer",
        "phploc\/phploc": "PHP Lines of Code",
        "atoum\/atoum": "Atoum",
        "jakub-onderka\/php-parallel-lint": "Parallel Linting Tool",
        "behat\/behat": "Behat BDD Testing",
        "hipchat\/hipchat-php": "Hipchat integration",
        "phptal\/phptal": "PHPTAL templating engine",
        "maknz\/slack": "Slack integration"
    }
}

**Comment by danbuntu** [comment]
and nows comes the embarrassing bit.
I've just looked through the above and got a feel for what's it's doing. I found the location for my docblock file and .... I hadn't made it executable. D'oh!
