### ISSUE TITLE
Allow to modify PHPCI configuration without modify versioned code

### ISSUE THREAD

**Issue by corretge** [Block8/PHPCI#781]
When we need to enable the Shell plugin, we should set the constant ENABLE_SHELL_PLUGIN to true inside the file vars.php.

The file vars.php is versioned and the changes in this file could be pushed.

Solutions proposed:

A)
In bootstrap.php before to require once vars.php, check if exists local_vars.php and if exists, require it. Then we can override these "vars" without compromise the repository.

local_vars.php should be gitignored.

B)
Duplicate the current vars.php to vars.dist.php and try to load vars.php if exists. The next step is to load vars.dist.php.

vars.php should be gitignored

**Comment by dancryer** [comment]
I like option A.

Feel free to implement and send a PR, you might as well get the credit. :+1:

**Comment by tvbeek** [comment]
I think option A is the best (if you use custom config files people can forget parts on update)
It should be nice if you could implement it and create a PR, It is something I had today on my local install.
