### ISSUE TITLE
console phpci:run-builds not working anymore

### ISSUE THREAD

**Issue by pulponair** [Block8/PHPCI#795]
Due to
https://github.com/Block8/PHPCI/commit/d481140ea2a4ffc4a07449b78a972d8352e7466c

console phpci:run-builds stops working since runCommand passes maxbuilds:
$store->getByStatus(0, $this->maxBuilds);

Which can be NULL which results in "....LIMIT 0"

**Comment by dancryer** [comment]
Working on this now. 

I'd strongly recommend against using the master branch for your own PHPCI installs, rather use an actual release build: https://github.com/Block8/PHPCI/releases

**Comment by pulponair** [comment]
Well i do not use it for production. Just currious of new features. So i do play arround from time to time ;)

**Comment by dancryer** [comment]
This is fixed in: https://github.com/Block8/PHPCI/commit/320b0efa7175b0271f1323553ab208615626843e :)
