### ISSUE TITLE
phpci:install gives MySQL error in MySQL 5.6

### ISSUE THREAD

**Issue by kevin-jones** [Block8/PHPCI#818]
During console installation I got the following error:

```
Setting up your database...
[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'log' can't have a default value
```
I'm running MySQL 5.6. Seems to be a bit of a MySQL bug and may relate to some kind of strict configuration.  More info here: http://sql-info.de/mysql/notes/gotchas/blob-text-column-cant-have-default-value.html

**Comment by marcin-derlukiewicz** [comment]
same here

**Comment by mikebronner** [comment]
Same here when trying to upgrade.

**Comment by mikebronner** [comment]
Solution I have used for MySql is to remove the default definition in the Migration script. This might not be applicable to other RDBMSs though. Probably warrants further investigation?

**Comment by cdburgess** [comment]
I noticed that the default was setting it to empty:
`'default' => ''`

I'm not sure how that would affect the functionality necessarily. When I removed those settings from `20140730143702_fix_database_columns.php` and `20150203105015_fix_column_types.php` the errors went away.

**Comment by xlilien** [comment]
+1 @cdburgess 

A little summary: 
The error occurs when setting database column to `text` type, with allowed `null` value and when trying to set the default value to empty string. I guess this is just a typo since in other similar cases in other migrations (`text` type column, allowed `null` value) there is used the `null` as default value.

**Comment by laurin1** [comment]
version 1.6 or below? 

I'm testing 1.7.0-beta2 and am getting the same error on installation.

**Comment by AlexStansfield** [comment]
I'm also getting this on 1.7.0-beta2

**Comment by xawiers** [comment]
Won't be fixed until alien invasion ?

**Comment by AlexStansfield** [comment]
Unfortunately it feels like this project has died off again.
