### ISSUE TITLE
Dashboard build dates all the same

### ISSUE THREAD

**Issue by benr77** [Block8/PHPCI#820]
PHPCI v1.60 but also noticed on previous release - On the Dashboard view, or even the Project view, the list of builds all show the current time and date, rather than the time of the actual build. Google Chrome Version 40.0.2214.115 (64-bit) on Linux Mint 17.1

**Comment by tvbeek** [comment]
Can you place a screenshot? Because if I understand you right I can reproduce it on my installation

**Comment by benr77** [comment]
![screenshot from 2015-02-25 11 10 40](https://cloud.githubusercontent.com/assets/2156742/6368691/50369638-bcdf-11e4-9c35-14539ac0695b.png)

It works fine in Firefox but in Chrome it's broken - I have Javascript errors which I think might be the cause of this - let me know if you want me to post them here too

**Comment by benr77** [comment]
Just to clarify the dates and times shown are always the current date and time

**Comment by tvbeek** [comment]
Now I see it, my default browser is Firefox.
But I can reproduce it in Chrome, IE and Safari

**Comment by adamazing** [comment]
I can reproduce, the value shown is the same across all builds. The
datetime attribute of the "time" element is correct in each case.

The timeline-item div:
<div class="timeline-item">
                                <span class="time"><i class="fa
fa-clock-o"></i> <time datetime="2015-02-19T13:54:40+1300"
data-format="LT">11:17 PM</time></span>
                                <h3 class="timeline-header">
                                    <a href="
http://phpci.fify.co/project/view/2">
                                        Nevi
     </a>
                                    -
                                    <a href="
http://phpci.fify.co/build/view/88">
                                        Build #88
         </a>
                                    -
                                    Failed
 </h3>

                                <div class="timeline-body">
                                    <a href="#" target="_blank">591d12b
()</a>                                    -
</div>
                            </div>

[image: Inline images 2]

**Comment by benr77** [comment]
Updated my local version and all is fixed. Thanks everyone.
