### ISSUE TITLE
Upgrade instructions improvements

### ISSUE THREAD

**Issue by benr77** [Block8/PHPCI#822]
The upgrade instructions are rather basic and don't currently work very well: https://www.phptesting.org/wiki/Updating-PHPCI

Obviously this project is evolving nice and rapidly with regular releases, so having a smooth upgrade path is highly desirable.

Suggestions:

* Don't use ```sudo``` as in most cases this probably won't be needed. Any instances where it is the user should know to add this.

* Running ```./console phpci:update``` just responds with an error "Column already exists: 1060 Duplicate column name 'ssh_private_key'" - I have never got this command to work.

* I've not found it necessary to re-add the plugins needed

**Comment by mavimo** [comment]
@benr77 thanks for the report, can you try to update the wiki?

**Comment by benr77** [comment]
I've now updated the wiki. I've let the line with `./console phpci:update` there as even though this is currently broken (for me at least) it is still a required step in the upgrade process.

I will submit a separate issue for the broken update command now.

**Comment by mavimo** [comment]
@benr77 ok, thx for upgrading https://github.com/Block8/PHPCI/wiki/Updating-PHPCI, this issue can be closed?
