### ISSUE TITLE
 fatal: ambiguous argument 'Manual^!'

### ISSUE THREAD

**Issue by toolpixx** [Block8/PHPCI#823]
Hi,

what does it mean? Now i have install phpci as the install-instructions say. Then i have refresh the install, too. But i will get the same error in build:

`RunCommand.ERROR: fatal: ambiguous argument 'Manual^!': unknown revision or path not in the working tree. Use '--' to separate paths from revisions`

What is my problem? Last day i have install it on my macbook then copied phpci to my server; this was running well. But this isn't a good option to install phpci.

Best regards

**Comment by toolpixx** [comment]
The problem does only show if i setup "test" in my config.

**Comment by dancryer** [comment]
Hi @toolpixx - If you pull from master now, this problem should be fixed. :+1:

**Comment by pdiveris** [comment]
Erm... I am having the same problem. I installed phpci using the .phar. Is the answer the same, do I need to pull from master?

**Comment by arall** [comment]
@pdiveris a pull from master fixed my problem.

**Comment by iget-master** [comment]
I'm having the same issue,

```
RUNNING PLUGIN: php_code_sniffer
fatal: ambiguous argument 'Manual^!': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git  [...] -- [...]'
```

I really dont understand this problem, could someone help-me?
