### ISSUE TITLE
Build takes a long time

### ISSUE THREAD

**Issue by craigwillis85** [Block8/PHPCI#824]
I have a small Silex application (containing 2 controllers and a couple of views).

When I set a build running and the console `phpci:run-builds` begins, it begins the clone from github, but seems to stay on this for a long time.

The console is currently on the following stage of the build

`[2015-02-25 12:19:17] RunCommand.INFO: Using --prefer-source flag {"buildID":"80"} []` which it has been since 12:19am (almost 45 minutes)

**Comment by dancryer** [comment]
@craigwillis85 That is composer running. Do you have a lot of dependencies?

**Comment by craigwillis85** [comment]
Not really.

After 45 minutes, I cancelled the build

**Comment by dancryer** [comment]
Maybe try adding `prefer_dist: true` under the `composer` section of your config.yml file, see if that speeds it up?

**Comment by craigwillis85** [comment]
I'll update the config and re-run

**Comment by craigwillis85** [comment]
@dancryer that seems to have sped up the build (takes ~5 minutes compared to ~45)

**Comment by kentpachi** [comment]
same problem here, where is that config.yml ? phpci.yml ? can i set prefer_dist: true straight in the textarea of the UI ? thx for help

**Comment by tvbeek** [comment]
It is in phpci.yml
```
setup:
    composer:
        action: "install"
        prefer_dist: true
```

**Comment by kentpachi** [comment]
thanks, trying right now

**Comment by kentpachi** [comment]
now i'm getting [2015-03-10 16:26:54] RunCommand.INFO: Using --prefer-dist flag {"buildID":"17"} []

so it seems that the parameter works, but its still really long 6 mins elapsed 

plus with the default installation i don't know really which tasks are performed exactly 

the project doesn't have that much dependencies 

```
"php": ">=5.3.3",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": ">=2.2.3,<2.4-dev",
        "doctrine/doctrine-bundle": "1.2.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.3.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/framework-extra-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "incenteev/composer-parameter-handler": "~2.0",
        "jms/serializer-bundle": "0.13.*",
        "friendsofsymfony/rest-bundle": "1.3.*", 
        "nelmio/cors-bundle":"~1.0",
        "friendsofsymfony/user-bundle": "~1.3"
```

what is the average time or the minimal build time for a project ?

**Comment by tvbeek** [comment]
The time depends on a couple  of things
1  the cloning of the project
2 the downloading of the dependencies
3 the actions you do with the code (test, checks, ...)
4 the size of your code (more code = everything takes longer)

1 depends a lot of the connection between your phpci and your git server
2 will be fast with the prefer_dist: true (except if you change your composer.lock file)
3 is what you have places in your phpci.yml file (and depends on the speed of your system)
4 is your code, not really possible to dump a part to speed it up ;)
