### ISSUE TITLE
[Bug] unknown level "all" in php-cs-fixer

### ISSUE THREAD

**Issue by wandersonwhcr** [Block8/PHPCI#833]
Olá pessoas (e outros)!

If we don't configure a `level` option in `php_cs_fixer`, the plugin will use an unknown `--level=all` parameter, unrecognized by `php-cs-fixer` binary (v1.4.2).

`
  [InvalidArgumentException]       
  The level "all" is not defined.
`

**Comment by mikebronner** [comment]
Confirmed, this should be an easy fix. If I don't get a PR within the next few days submitted, please feel free to do so.

PHPCI/Plugin/PhpCsFixer.php should probably read:

```php
    protected $workingDir = '';
    protected $level      = ' --level=psr2';
    protected $verbose    = '';
    protected $diff       = '';
    protected $levels     = array('psr0', 'psr1', 'psr2', 'symfony');
```

I will update the wiki in the mean time.
