### ISSUE TITLE
Technical Debt plugin does not display results

### ISSUE THREAD

**Issue by benr77** [Block8/PHPCI#840]
When a build is run with the Technical Debt plugin, the log contains results from the plugin but these results are not displayed in the interface. The Technical Debt table is shown, with the header etc, but there are no data rows containing the matches that have been found and are shown in the log.

**Comment by jfi** [comment]
Hi @benr77, what version of PHPCI are you running?

**Comment by benr77** [comment]
The very latest 1.6.0

**Comment by mryanb** [comment]
I am also running 1.6.0 and am receiving and empty table. It looks like the plugin is running according to the build log.

`RUNNING PLUGIN: technical_debt
Found TODO on line 222 of /scripts/upgrade.php:`

**Comment by aardvarklondon** [comment]
Yep exactly the same for me. Possibly a JS error

[Error] TypeError: null is not an object (evaluating 'errors.length')
	onUpdate (technical_debt.js, line 48)
	(anonymous function) (technical_debt.js, line 14)
	dispatch (jquery.js, line 4409)
	handle (jquery.js, line 4095)
	trigger (jquery.js, line 4324)
	(anonymous function) (jquery.js, line 4875)
	each (jquery.js, line 375)
	each (jquery.js, line 139)
	trigger (jquery.js, line 4874)
	success (build.js, line 40)
	fire (jquery.js, line 3073)
	fireWith (jquery.js, line 3185)
	done (jquery.js, line 8251)
	(anonymous function) (jquery.js, line 8598)

**Comment by REBELinBLUE** [comment]
Yep exactly the same for me. Possibly a JS error

[Error] TypeError: null is not an object (evaluating 'errors.length')
onUpdate (technical_debt.js, line 48)
(anonymous function) (technical_debt.js, line 14)
dispatch (jquery.js, line 4409)
handle (jquery.js, line 4095)
trigger (jquery.js, line 4324)
(anonymous function) (jquery.js, line 4875)
each (jquery.js, line 375)
each (jquery.js, line 139)
trigger (jquery.js, line 4874)
success (build.js, line 40)
fire (jquery.js, line 3073)
fireWith (jquery.js, line 3185)
done (jquery.js, line 8251)
(anonymous function) (jquery.js, line 8598)

**Comment by njovin** [comment]
I'm experiencing the same issue - technical debt items are displaying in the build log but not on the web page. I dug in a bit more and all entries for tehcnical_debt-data in the build_meta mysql table have null values, so it appears the detected debt items aren't being stored to mysql properly.

**Comment by jfi** [comment]
I'll see if I can find time to fix this today.

On Mar 5, 2015, at 8:00 AM, njovin <notifications@github.com> wrote:

I'm experiencing the same issue - technical debt items are displaying in
the build log but not on the web page. I dug in a bit more and all entries
for tehcnical_debt-data in the build_meta mysql table have null values, so
it appears the detected debt items aren't being stored to mysql properly.

—
Reply to this email directly or view it on GitHub
<https://github.com/Block8/PHPCI/issues/840#issuecomment-77321852>.
