### ISSUE TITLE
Controller does not have action

### ISSUE THREAD

**Issue by lakshmi28gsrl** [Block8/PHPCI#874]
Hi,
Iam getting this error when using http://localhost/phpci/ url.

I have added .htaccess and also virtual host and getRequestPath() code is also correct

Can any one help me regarding this. Please I need support from you.

![Uploading error.png . . .]()

**Comment by mavimo** [comment]
@lakshmi28gsrl can you add some more info (webserver, php version, ...) and better explanation of the error?

**Comment by lakshmi28gsrl** [comment]
My problem is solved.

**Comment by dancryer** [comment]
Hi @lakshmi28gsrl 

Can you please explain how you resolved your initial problem?

Your new problem is because either:

1. Git is not installed on the machine that you're using to run PHPCI

or 

2. PHPCI can't find and/or can't execute Git (perhaps doesn't have the right permissions)

**Comment by lakshmi28gsrl** [comment]
Hi dancryer

thanks, I will check my git problem.

My problem solved in below way

First have installed in localhost and set virtual host and add rewrite urls in htaccess but I user url as
http://localhost/phpci. Then iam getting that error page. 

So I searched online for installation instructions to know where I was wrong then I find http://blog.erlem.fr/symfony2/127-symfony2-jobeet-l-usine-logicielle

This was very good I followed every step.Now Iam using url http://phpci.local and set server name in  hosts file in C:\Windows\System32\drivers\etc after that I restart the server.

Now it is working fine in windows.

Actually I thought that you guys please provide some more detail document. Because due to lack of documentation it took 4 days to install. If we have correct documentation like the site I mentioned above it took only15 minutes.

Any way this tool was very nice Iam learning a lot more.

thanks

**Comment by lakshmi28gsrl** [comment]
after  fixing my  git problem Iam getting below error and "fails"

Cloning into 'C:\xampp\htdocs\phpci/PHPCI/build/21'...

Exception: Warning: trim() expects parameter 1 to be string, array given in C:\xampp\htdocs\phpci\vendor\symfony\yaml\Symfony\Component\Yaml\Parser.php line 237
