### ISSUE TITLE
Intent to implement: command to create a new build

### ISSUE THREAD

**Issue by jdecool** [Block8/PHPCI#879]
Intent to implement: command to create a new build

It could be interesting to create a build from a command.

The command could be like :
```bash
./console phpci:create-build [projectId]
```

With this command, it could be easy to create a build from a CRON task.

What do you think about it ?

**Comment by mavimo** [comment]
@jdecool Is currently possible using cURL, eg:
```
curl http://phpci.example.com/webhook/git/<project_id>
```

more info on [wiki page](https://github.com/Block8/PHPCI/wiki/Autobuilding-from-Git-by-Cron)

Having a specific command can be a plus.

**Comment by mikedamoiseau** [comment]
I also think it would be nice to have a command to create a new build from the command line :)
