### ISSUE TITLE
Missing JS Includes

### ISSUE THREAD

**Issue by mikebronner** [Block8/PHPCI#903]
The following files appear to be missing site-wide:

`/assets/js/sprintf.min.map`
`/assets/js/plugins/datepicker/locales/bootstrap-datepicker.en.js`

**Comment by mavimo** [comment]
@mikebronner *.map files (also know as [sourcemap](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/) ) are not required, are just requested from your browser when you enable developer tools, so is not an issue.

**Comment by mikebronner** [comment]
I agree, but I don't think it's good to have JS errors show in the browser. Optimally there should be no console errors, and at most warnings.

(I would attach a screenshot here, but GitHub seems to have disabled that for now, or the DDOS attack is interfering.)

**Comment by mikebronner** [comment]
I agree, but I don't think it's good to have JS errors show in the browser. Optimally there should be no console errors, and at most warnings.

(I would attach a screenshot here, but GitHub seems to have disabled that for now, or the DDOS attack is interfering.)

**Comment by mikebronner** [comment]
Addressed in #1079 and #1078
