### ISSUE TITLE
Latest builds show current time not build time

### ISSUE THREAD

**Issue by alasdairdc** [Block8/PHPCI#920]
In the Dashboard the date separator and time shown against the 'Latest builds' shows current date / time respectively not the (completed) build date / time as expected.

This is using the packaged version for Wheezy.

**Comment by mavimo** [comment]
@alasdairdc I'm testing the master and I can't see the issue so I suppose you are using an old version of PHPCI, can you give us info about the version are you using (sorry, I don't know the Wheezy package version).

**Comment by alasdairdc** [comment]
correction it's version 1.6.0

please see screenshot:

![screenshot from 2015-04-17 19 51 17](https://cloud.githubusercontent.com/assets/2862157/7208792/353e3ce4-e53b-11e4-814a-8654767cb4e7.png)

**Comment by mavimo** [comment]
Is already fixed on master, please try to switch (only for testing) and let us know if you can continue to reproduce the issue.

![dashboard](https://cloud.githubusercontent.com/assets/43941/7215454/1e2af850-e5d9-11e4-92cc-2b3ec9281b6a.png)

**Comment by alasdairdc** [comment]
did a git clone (to a diff directory)  setup using existing DB same issue.

**Comment by alasdairdc** [comment]
ah it seems to a browser issue...Chromium 37.0. 2062.120-1~deb7u1 shows like the screenshot I posted.  Iceweasel (Firefox on Debian) 31.5.3esr-1~deb7u1 shows correctly as per your screenshot.

**Comment by alasdairdc** [comment]
was just my chromium, sorry for the false report. Closing...
