### ISSUE TITLE
SMTP Password not masked

### ISSUE THREAD

**Issue by Esuk** [Block8/PHPCI#921]
In 1.6 under Admin -> Settings -> Email settings - SMTP Password is not masked, it shows the password in clear text.

![settings](https://cloud.githubusercontent.com/assets/1926737/7207350/0eadfada-e539-11e4-8c7c-2066a3fd6580.png)

**Comment by mavimo** [comment]
Can you create a PR, only needed to change ( on file ```PHPCI/Controller/SettingsController.php``` line 332 ): 
```php
$field = new Form\Element\Text('smtp_password');
```
to 
```php
$field = new Form\Element\Password('smtp_password');
```
and test all work fine.
