### ISSUE TITLE
Build log readability issues

### ISSUE THREAD

**Issue by leewillis77** [Block8/PHPCI#936]
In a recent change it looks like the build log is generated / styled differently. The current implementation is pretty much unreadable, screenshots below:

![image](https://cloud.githubusercontent.com/assets/1097338/7300475/4fd86492-e9d4-11e4-8280-181c117529b8.png)

Notice the dark red text and dark green text is very difficult to read. 

I've tweaked some style in ansi-colors.css on my local install to make this readable, but they're probably still not perfect, so no PR at this stage. Is this something still being worked on?

**Comment by leewillis77** [comment]
For reference, my ansi-colors.css is [here](https://gist.github.com/leewillis77/61d695e83d1656219c76). This swaps *red* for *orangered*, and *green* for *lawngreen*, as well as making both **bold**. Quite a lot of inconsistencies in this though - for example I've only changed the FG colours, not BG, and "red" is probably now "brighter" than "brred", so would need more work before being committed.

**Comment by Adirelle** [comment]
I added a default but ugly color theme when I made the PR. I'm not attached to the black background. Can you tell me if the following CSS is better please ? https://gist.github.com/Adirelle/46a854f538a55706ab2f

**Comment by leewillis77** [comment]
Yep - much better - thanks - although I'm somewhat against defining black as white  (.ansi_color_bg_black { background-color: #FFF }) - I'd much rather see the classes be appropriate - can we do that?

**Comment by Adirelle** [comment]
This would be possible but it would require more than just changing a stylesheet, namely create a SensioLabs\AnsiConverter\AnsiToHtmlConverter subclass only to override the $colorNames attribute. SensioLabs didn't even bother with this when providing their themes.

**Comment by leewillis77** [comment]
Ooh, nice, just looked at that. Seems like a stylesheet is the "proper" way to do it. Oh well!

**Comment by leewillis77** [comment]
This was fixed by https://github.com/Block8/PHPCI/commit/8bf1d09afdf56c1557502e50b8291716f1cf4f96 as far as I can tell.
