### ISSUE TITLE
Use phing plugin  failed?

### ISSUE THREAD

**Issue by yuwenhui** [Block8/PHPCI#943]
This is my build log:

    Initialized empty Git repository in /.git/
    Working copy created: /
    RUNNING PLUGIN: mysql
    PLUGIN: SUCCESS
    RUNNING PLUGIN: phing
    Could not find phing
    PLUGIN: FAILED
    RUNNING PLUGIN: email
    1 emails sent
    0 emails failed to send
    PLUGIN: SUCCESS
    BUILD FAILED
    Removing Build.

I've installed Phing correctly and can use `phing build:test` in the terminal.How can this be fixed?
I'm tring to run corretgecom's test form <https://github.com/corretgecom/phpci_issue748>,and it is also failed.My phpci.yml like this:

    build_settings:
      verbose: false
      clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone 
      ignore:
        - "vendor"
        - "Tests"

    setup:
      mysql:
        - "DROP DATABASE IF EXISTS test;"
        - "CREATE DATABASE test;"
        - "GRANT ALL PRIVILEGES ON test.* TO test@'localhost' IDENTIFIED BY 'test';"
    test:
      phing:
        directory: ''
        build_file: 'build.xml'
        targets:
          - "build:test"
        properties:
          config_file: "PHPCI"

    failure:
      email:
        committer: true
        cc: ["php-ci@googlegroups.com"]

**Comment by adamazing** [comment]
Hi Max, 
When you run phing in a terminal which user are you running it as? 
Are you starting them manually by running "./console phpci:run-builds" at the command line? Or do you have a cron job running the phpci builds? Which user do you run the command as?/Which user's crontab contains the cron job?

Make sure "phing" is in the path of the user whose crontab is kicking off the build process.

**Comment by yuwenhui** [comment]
Hi Adam,

I've added a cron job like this:
`* * * * * /usr/bin/php /home/wwwroot/phpci/console phpci:run-builds`
I'm not sure is it correctly.

**Comment by adamazing** [comment]
Did you add it by typing:
" crontab -e" as a logged-in user?
If so, which user, if not, which file did you add it to?

It sounds like the phing executable has been installed (since it works)
when you run it from the command line, but when phpci runs it can't find
the executable.

I've seen a couple of example crontabs that explicitly set "PATH" to be
"/usr/bin:/usr/local/bin....etc..." but don't include "~/composer/bin/...."
or whatever. So if phing is installed as user X in user X's home/composer
dir, they'd be able to run phing at the command line, but when their
crontab ran, it wouldn't be able to find the executable.

**Comment by yuwenhui** [comment]
Yes,I added the cron job by typing `crontab -e` use the root user.Let me try to restart the server and the cron job.

**Comment by yuwenhui** [comment]
Hi Adam,

I think I may have found the problem.
It seems that phpci could not found the phing binary path correctly.
![phing](https://cloud.githubusercontent.com/assets/1715211/7332963/6124469c-eb8e-11e4-88af-1e0d3cb94d1e.png)

The phing not exist neither in `APPLICATION_PATH` nor in `APPLICATION_PATH . 'vendor/bin/'`,and `shell_exec('which ' . $bin)` return null.

So I copy the phing located in `/usr/local/php/bin/phing` to  `APPLICATION_PATH . 'vendor/bin/'`,and the building jobs run well.

I don't know why `shell_exec('which ' . $bin)` return null. I added `echo shell_exec('date' )` in PluginController.php to test and it returned right, but could't execute `which phing`.

**Comment by mavimo** [comment]
I suggest to don't copy phink in the vendor/bin but add phing to your ```composer.json```:

    composer require phingofficial/phing

Can we ask for your help to investigate the which command issue? can you create a new PHP file with:

```php
<?php
var_dump(shell_exec('which ls'));
var_dump(shell_exec('which phing'));
```

and execute with:

```
php YOURFILE.php
```

then send us the result? Thank you!

**Comment by Adirelle** [comment]
@yuwenhui Which version of PHPCI are you using ? The code you pasted seems pretty old.

By the way, please does not run builds as root. Malevolent developpers aside, you're not protected against big errors during the tests. It would be better to run them as unprivilegied users to circumvent critical failures.

**Comment by adamazing** [comment]
@yuwenhui 
Sorry, I didn't see those images last night, I was on my phone. 

Further to @mavimo 's suggestion, add it as a cron job too and I'll bet you see a difference, e.g.
```bash
* * * * * /usr/bin/php /path/to/YOURFILE.php >/path/to/YOURFILE.log 2>&1
```
Then check the contents of that log file.

Make sure you set a PATH somehow in the cron job, e.g. I have a user "phpci" whose crontab looks something like:
```bash
PATH=/home/phpci/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
*/5 * * * * /usr/bin/php /srv/www/phpci/console phpci:run-builds >/dev/null 2>&1
```

:+1: to @Adirelle's suggestion to avoid running as root.

**Comment by Adirelle** [comment]
PHPCI automatically search in PHPCI_DIR (where you've installed it), PHPCI_DIR/vendor/bin, BUILD_PATH and BUILD_PATH/vendor/bin (if BUILD_PATH/composer.json exists). So you should be able to install phing using composer, either in PHPCI vendors or in the project composer.json, if you are using it.

**Comment by yuwenhui** [comment]
@mavimo  Think you, mavimo, I didn't execute the PHP file with `php YOURFILE.php`.
I added the follow   
    
    <?php
    var_dump(shell_exec('which ls'));
    var_dump(shell_exec('which phing'));

in "Phing.php" which located in `/phpci/PHPCI/Plugin/Phing.php`,and dumped it in the browser.

It seems that I could not install PHPCI completely as some reasons of network. Some package could not download form GITHUB. I'll try to install it again.

**Comment by yuwenhui** [comment]
@Adirelle Think you, Adirelle. I made a stupid mistake yesterday. The code I pasted was an old version I installed in my dev environment a few months ago. I have installed the latest version of PHPCI.

**Comment by mavimo** [comment]
@yuwenhui If you think is "not a big" please close this issue.
