### ISSUE TITLE
Language selector has no effect

### ISSUE THREAD

**Issue by vladimmi** [Block8/PHPCI#955]
Just installed 1.6.0. Admin panel is on Russian (detected as default from browser I guess) and cannot be switched to any other - setting shows selected language while interface remains the same.

**Comment by mavimo** [comment]
Can you test also on master and update us if the bug is reproducible?

**Comment by vladimmi** [comment]
Sure. Just installed from master - bug is still here. https://goo.gl/KFVc62 - as you can see, English selected (default one), but interface is on Russian. If select another language and save - have a message "Settings saved" and everything remains the same.

**Comment by Adirelle** [comment]
This settings is the default language, i.e. when using PHPCI from the command line (building) or when the browser doesn't send any "ACCEPT_LANGUAGE" header. For the website, this can be overriden from your account setting page.

This should maybe be properly labeled and explained.
