### ISSUE TITLE
Poll github command - only looking at master

### ISSUE THREAD

**Issue by craigwillis85** [Block8/PHPCI#956]
Hi

I was wondering if the `poll-github` command only gets the latest commits from master?

I have a project, that in the default branch name is a different branch from master, but when I run the `poll-github` command, it only displays the latest commit to master

Thanks

**Comment by tvbeek** [comment]
What is your setting for the default branch in phpci?
If I check https://github.com/Block8/PHPCI/blob/master/PHPCI/Command/PollCommand.php#L51 I think it only creates builds for the default branch.

**Comment by craigwillis85** [comment]
My default branch is not master

Looking through the github commits api, If you don't pass it a branch as a parameter, it will always use master

https://developer.github.com/v3/repos/commits/

`"SHA or branch to start listing commits from. Default: the repository’s default branch (usually master)."`

So my branch that I'm on has a commit hash of `xxxx12345aaa` for example

Master currently has a commit hash of `ccc333555trrrr` for example

When I run the command `./console phpci:poll-github` I always get the following:

`Last commit to GitHub for Project X is ccc333555trrrr`

This means that the polling isn't taking into effect my default branch

**Comment by tvbeek** [comment]
It always use the default, but in the settings you can change the default branch. (The github settings)

**Comment by craigwillis85** [comment]
Surely there should be a way of overriding this? I have a staging branch where I merge feature branches into and then run the branch using PHPCI.

I'd like to poll when this branch changes in Github. Currently, the PollCommand does not allow this.

What settings are you referring to? Project settings on the global admin settings?

**Comment by tvbeek** [comment]
I mean the repository settings on github.
See https://help.github.com/articles/setting-the-default-branch/

**Comment by craigwillis85** [comment]
I still use master in production. I have a couple of branches that I use (Testing and QA), so it'd be nice to actually poll for changes in either of these branches.

I guess my only option is to manually build and then use the `rebuild` command which will build the branch no matter what has been merged in

**Comment by tvbeek** [comment]
You can also use the github hook and not the polling. Or is your phpci installation not reachable from outside?

**Comment by craigwillis85** [comment]
It is reachable. Ideally what I wanted, was to poll gitbub at lets say 5pm and if any new commits were made, build.

The hook will get called as soon as I push though, right?

**Comment by tvbeek** [comment]
The hook will create a build but not start the build, that will be done with a daemon or cronjob. If you start the cronjob on the specified time it will start the builds on that moment. Or do you have other projects that you want to run?

Else you could create pull request with a change in the pollcommand to get the commits from the specified branch (or all branches)

**Comment by craigwillis85** [comment]
The hook might be an option. I'll only be committing maybe once or twice a day to that particular branch.

I only have 1 project currently.

I still think the poll command should be able to take a specified branch, I'll have a look at maybe raising a pull request for that
