### ISSUE TITLE
No results shown after a complete build

### ISSUE THREAD

**Issue by Henk8** [Block8/PHPCI#960]
After a complete build the results are not shown in the detail page of a commit. There are no errors and when I run the plugins manualy everything is fine.

The tests that are performed are:
- Codeception
- Copy paste detector
- PHPLoc
- DocBlockParser

The logs are correctly stored in the database, but not shown.

Build log:
```
Working copy created: /
RUNNING PLUGIN: php_loc
phploc 2.0.6 by Sebastian Bergmann.
Size
  Lines of Code (LOC)                               91
  Comment Lines of Code (CLOC)                      44 (48.35%)
  Non-Comment Lines of Code (NCLOC)                 47 (51.65%)
  Logical Lines of Code (LLOC)                      13 (14.29%)
    Classes                                         11 (84.62%)
      Average Class Length                          11
      Average Method Length                          1
    Functions                                        0 (0.00%)
      Average Function Length                        0
    Not in classes or functions                      2 (15.38%)
Complexity
  Cyclomatic Complexity / LLOC                    0.00
  Cyclomatic Complexity / Number of Methods       1.00
Dependencies
  Global Accesses                                    0
    Global Constants                                 0 (0.00%)
    Global Variables                                 0 (0.00%)
    Super-Global Variables                           0 (0.00%)
  Attribute Accesses                                 9
    Non-Static                                       9 (100.00%)
    Static                                           0 (0.00%)
  Method Calls                                       9
    Non-Static                                       9 (100.00%)
    Static                                           0 (0.00%)
Structure
  Namespaces                                         0
  Interfaces                                         0
  Traits                                             0
  Classes                                            1
    Abstract Classes                                 0 (0.00%)
    Concrete Classes                                 1 (100.00%)
  Methods                                            9
    Scope
      Non-Static Methods                             9 (100.00%)
      Static Methods                                 0 (0.00%)
    Visibility
      Public Methods                                 7 (77.78%)
      Non-Public Methods                             2 (22.22%)
  Functions                                          0
    Named Functions                                  0 (0.00%)
    Anonymous Functions                              0 (0.00%)
  Constants                                          0
    Global Constants                                 0 (0.00%)
    Class Constants                                  0 (0.00%)
PLUGIN: SUCCESS
BUILD SUCCESS
Removing Build.
```

![noresults](https://cloud.githubusercontent.com/assets/11833224/7431500/5dd134ec-f01f-11e4-93af-9db5cdd8eb9c.png)

**Comment by Adirelle** [comment]
Might be a javascript error. Can you reload the page with the navigator developper tools enabled, and showing the javascript console ?

**Comment by Henk8** [comment]
The javascript error is:
SyntaxError: Unexpected token < http://phpci.nl/assets/js/plugins/datepicker/locales/bootstrap-datepicker.en.js:1

If I set PHPCI to another language I haven't got a script error, but no results either. It looks like the Javascript error isn't the issue.

**Comment by Adirelle** [comment]
Is it the only javascript error, or the first ?

**Comment by Henk8** [comment]
That was the only javascript error. In the error log I found the following:

Fatal error:  Class 'PHPCI\\Controller' not found in vendor/block8/b8framework/b8/Application.php on line 93.

After debugging it looks like he want's to load the class: PHPCI\Controller\BuildController but with no succes.


Full error report:
2015/05/06 10:12:20 [error] 16004#0: *28482 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'PHPCI\\Controller' not found in /var/www/phpci.nl/vendor/block8/b8framework/b8/Application.php on line 93
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/phpci.nl/public/index.php:0
PHP message: PHP   2. PHPCI\Application->handleRequest() /var/www/phpci.nl/public/index.php:16
PHP message: PHP   3. b8\Application->handleRequest() /var/www/phpci.nl/PHPCI/Application.php:88
PHP message: PHP   4. b8\Application->getController() /var/www/phpci.nl/vendor/block8/b8framework/b8/Application.php:69
PHP message: PHP   5. PHPCI\Application->loadController() /var/www/phpci.nl/vendor/block8/b8framework/b8/Application.php:85
PHP message: PHP   6. b8\Application->loadController() /var/www/phpci.nl/PHPCI/Application.php:124" while reading response header from upstream, client: 192.168.1.187, server: phpci.nl, request: "GET /assets/js/sprintf.min.map HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "phpci.nl", referrer: "http://phpci.nl/build/view/36"

**Comment by Adirelle** [comment]
*.map files are optionally loaded when debugging javascript in a browser. They are not required. However, the b8 framework doesn't gracefully handle 404...

**Comment by steverobbins** [comment]
@Henk8 I'm getting this JS error, too.  See #999

**Comment by Henk8** [comment]
I have found the problem. In the server config file I missed the following (nginx):
fastcgi_param SCRIPT_NAME index.php;
In the "location @phpci" section.

I hope this could help you.
