### ISSUE TITLE
PHPMD custom ruleset not working

### ISSUE THREAD

**Issue by lukzgois** [Block8/PHPCI#964]
I'm trying to use a custom ruleset in PHP Mess Detector. On the doc it said the path will be relative to the PHPMD ruleset, so I've created a folder in the ruleset directory, but PHPCI said "Cannot find specified rule-set". I've tried both the relative and the absolute path.

Some solution for this?

**Comment by lukzgois** [comment]
I found the error. The custom rules aren't relative to the PHPMD rules, it's relative to the build root. I think this need to be changed in the doc to avoid confusion.

**Comment by mavimo** [comment]
@lukzgois can you update the wiki and close this issue? Thx!

**Comment by mikebronner** [comment]
Just checked the wiki: it has two variables:
- path
- custom rulesets array

If path is left blank, it will use the build root, otherwise it will use the path specified as the starting point. Is that not correct? Perhaps it needs to be worded more clearly?

**Comment by lukzgois** [comment]
I see this page: https://www.phptesting.org/wiki/PHP-Mess-Detector-Plugin
Maybe just add "the rules will be relative to the path configuration or the project root if no path is configured". Something like this.

**Comment by mikebronner** [comment]
@mavimo I tried to get access to the forums, but have not gotten a reply. Who should I contact on that?

@lukzgois I have been updating the github wikis. I will try to see what needs to be done to get them in sync (I assumed the other wikis were generated from the github wiki pages). maybe this will help in the interim: https://github.com/Block8/PHPCI/wiki/Php-mess-detector-plugin

**Comment by lukzgois** [comment]
Great :smile: 
I'm setting up a new PHPCI installation in my company, so if I found other wiki issues I will send a revision to this pages :smile: hehe
Thanks for the help @mikebronner.
