### ISSUE TITLE
Run PHPCI

### ISSUE THREAD

**Issue by priyasubramaniyam** [Block8/PHPCI#968]
Hi all,
  Am insatlled the phpci following these instruction https://github.com/Block8/PHPCI/wiki/Installing-PHPCI 
i did upto User account created!...but i don't know how to run tool any one help me...

**Comment by mavimo** [comment]
@priyasubramaniyam take a look to wiki page:

 * https://github.com/Block8/PHPCI/wiki/Adding-PHPCI-Support-to-Your-Projects
