### ISSUE TITLE
SQL error during installation

### ISSUE THREAD

**Issue by phackwer** [Block8/PHPCI#977]
I tried to install PHPCI. During install I've got this error:

Setting up your database... 

                                                                                                             
  [PDOException]                                                                                             
  SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'log' can't have a default value  
                                                                                                             
Aparently, there's a error on your SQL script.

So, when I tried to login, I've got all kind of issues.

Tried to reinstall it fixing your sql script. Couldn't find it. :-D So, tried to check how you build the database. Found phinx. made a mitake looking for sphinx. Tried again to look for phinx. Found it. Learned something new. So, I'm trying to see if it's a PHPCI bug or Phinx bug.

Anyway, you should fix it. Problably didn't happen only for me.

**Comment by phackwer** [comment]
Found the bug: your code.

fix_database_columns.php

<?php

use Phinx\Migration\AbstractMigration;

class FixDatabaseColumns extends AbstractMigration
{
    /**
     * Migrate Up.
     */
    public function up()
    {
        $dbAdapter = $this->getAdapter();

        if ($dbAdapter instanceof \Phinx\Db\Adapter\PdoAdapter) {
            $pdo = $dbAdapter->getConnection();
            $pdo->exec('SET foreign_key_checks = 0');
        }

        $build = $this->table('build');
        $build->changeColumn('project_id', 'integer', array('null' => false));
        $build->changeColumn('commit_id', 'string', array('limit' => 50, 'null' => false));
        $build->changeColumn('status', 'integer', array('null' => false));
        $build->changeColumn('log', 'text', array('null' => true));
        $build->changeColumn('branch', 'string', array('limit' => 50, 'null' => false, 'default' => 'master'));
        $build->changeColumn('created', 'datetime', array('null' => true));
        $build->changeColumn('started', 'datetime', array('null' => true));
        $build->changeColumn('finished', 'datetime', array('null' => true));
        $build->changeColumn('committer_email', 'string', array('limit' => 512, 'null' => true));
        $build->changeColumn('commit_message', 'text', array('null' => true));
        $build->changeColumn('extra', 'text', array('null' => true));

        $buildMeta = $this->table('build_meta');
        $buildMeta->changeColumn('project_id', 'integer', array('null' => false));
        $buildMeta->changeColumn('build_id', 'integer', array('null' => false));
        $buildMeta->changeColumn('meta_key', 'string', array('limit' => 250, 'null' => false));
        $buildMeta->changeColumn('meta_value', 'text', array('null' => false));

        $project = $this->table('project');
        $project->changeColumn('title', 'string', array('limit' => 250, 'null' => false));
        $project->changeColumn('reference', 'string', array('limit' => 250, 'null' => false));
        $project->changeColumn('branch', 'string', array('limit' => 50, 'null' => false, 'default' => 'master'));
        $project->changeColumn('ssh_private_key', 'text', array('null' => true));
        $project->changeColumn('ssh_public_key', 'text', array('null' => true));
        $project->changeColumn('type', 'string', array('limit' => 50, 'null' => false));
        $project->changeColumn('access_information', 'string', array('limit' => 250, 'null' => true, 'default' => null));
        $project->changeColumn('last_commit', 'string', array('limit' => 250, 'null' => true, 'default' => null));
        $project->changeColumn('ssh_public_key', 'text', array('null' => true));
        $project->changeColumn('allow_public_status', 'integer', array('null' => false, 'default' => 0));

        $user = $this->table('user');
        $user->changeColumn('email', 'string', array('limit' => 250, 'null' => false));
        $user->changeColumn('hash', 'string', array('limit' => 250, 'null' => false));
        $user->changeColumn('is_admin', 'integer', array('null' => false, 'default' => 0));
        $user->changeColumn('name', 'string', array('limit' => 250, 'null' => false));

        if ($dbAdapter instanceof \Phinx\Db\Adapter\PdoAdapter) {
            $pdo = $dbAdapter->getConnection();
            $pdo->exec('SET foreign_key_checks = 1');
        }
    }
}

**Comment by phackwer** [comment]
And fix_columns_types.php

<?php

use Phinx\Db\Adapter\MysqlAdapter;
use Phinx\Migration\AbstractMigration;

class FixColumnTypes extends AbstractMigration
{
    /**
     * Migrate Up.
     */
    public function up()
    {
        // Update the build log column to MEDIUMTEXT:
        $build = $this->table('build');
        $build->changeColumn('log', 'text', array(
            'null' => true,
            // 'default' => '',
            'limit' => MysqlAdapter::TEXT_MEDIUM,
        ));

        // Update the build meta value column to MEDIUMTEXT:
        $buildMeta = $this->table('build_meta');
        $buildMeta->changeColumn('meta_value', 'text', array(
            'null' => false,
            'limit' => MysqlAdapter::TEXT_MEDIUM,
        ));
    }
}

**Comment by phackwer** [comment]
The code problably wasn't buggy on previous MySQL versions.

**Comment by phackwer** [comment]
No, still got the same error, and so got no load on the database which ends aways on 

"Sorry, there was a problem

Could not connect to any read servers."

**Comment by phackwer** [comment]
Aparently someone fixed the first file, but not the second. The default value for log must be removed on 

 fix_columns_types.php

**Comment by mikebronner** [comment]
See also #818

**Comment by Jamlee** [comment]
remove the default value to: $build->changeColumn('log', 'text', array('null' => true)); within file  fix_database_columns.php. and everything is OK.

**Comment by AlexStansfield** [comment]
@dancryer this is happening on 1.7.0-beta2 for me

**Comment by jonnylor63** [comment]
Thank you @phackwer same issue, same solution
For information the i try to install on vagrant/homestead server
