### ISSUE TITLE
bootstrap-datepicker.en.js Missing

### ISSUE THREAD

**Issue by steverobbins** [Block8/PHPCI#999]
The application is trying to include `assets/js/plugins/datepicker/locales/bootstrap-datepicker.en.js` which doesn't seem to exist, which results in a controller error

> Fatal error: Class 'PHPCI\\Controller' not found in /var/www/PHPCI/vendor/block8/b8framework/b8/Application.php on line 93

![http://i.imgur.com/ETB4Vu2.png](http://i.imgur.com/ETB4Vu2.png)

**Comment by Henk8** [comment]
I have found the problem. In the server config file I missed the following (nginx):
fastcgi_param   SCRIPT_NAME index.php;
In the "location @phpci" section.

I hope this could help you.

**Comment by mikebronner** [comment]
@steverobbins This should be addressed in PR #1078
